<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 From chi-squared to somers’ d | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</title>
  <meta name="description" content="This is the preface of the workbook" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 From chi-squared to somers’ d | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the preface of the workbook" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 From chi-squared to somers’ d | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  
  <meta name="twitter:description" content="This is the preface of the workbook" />
  

<meta name="author" content="Michael Strausz" />


<meta name="date" content="2025-08-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inferences.html"/>
<link rel="next" href="pearsons-r.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Are You Ready for R?</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="whats-new-in-version-3.html"><a href="whats-new-in-version-3.html"><i class="fa fa-check"></i>What’s new in version 3.0?</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#why-r"><i class="fa fa-check"></i><b>1.1</b> Why R?</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#class-project"><i class="fa fa-check"></i><b>1.2</b> Create a project for this class</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#add-files"><i class="fa fa-check"></i><b>1.3</b> Add the course files to your project</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#using-the-console"><i class="fa fa-check"></i><b>1.4</b> Using the Console</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="getting-started.html"><a href="getting-started.html#rules-about-naming-objects"><i class="fa fa-check"></i><b>1.4.1</b> Rules about naming objects</a></li>
<li class="chapter" data-level="1.4.2" data-path="getting-started.html"><a href="getting-started.html#common-practices-when-naming-objects"><i class="fa fa-check"></i><b>1.4.2</b> Common practices when naming objects</a></li>
<li class="chapter" data-level="1.4.3" data-path="getting-started.html"><a href="getting-started.html#about-vectors"><i class="fa fa-check"></i><b>1.4.3</b> About vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#first-script"><i class="fa fa-check"></i><b>1.5</b> Writing your first R script</a></li>
<li class="chapter" data-level="1.6" data-path="getting-started.html"><a href="getting-started.html#wont-load"><i class="fa fa-check"></i><b>1.6</b> What do to if the “load” command doesn’t load the dataframe</a></li>
<li class="chapter" data-level="1.7" data-path="getting-started.html"><a href="getting-started.html#review-of-this-chapters-commands"><i class="fa fa-check"></i><b>1.7</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>2</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tidyverse.html"><a href="tidyverse.html#install-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Installing packages</a></li>
<li class="chapter" data-level="2.2" data-path="tidyverse.html"><a href="tidyverse.html#exploring"><i class="fa fa-check"></i><b>2.2</b> Exploring dataframes</a></li>
<li class="chapter" data-level="2.3" data-path="tidyverse.html"><a href="tidyverse.html#org-script"><i class="fa fa-check"></i><b>2.3</b> Organizing your scripts</a></li>
<li class="chapter" data-level="2.4" data-path="tidyverse.html"><a href="tidyverse.html#welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>2.4</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="tidyverse.html"><a href="tidyverse.html#introducing-the-pipe-in-tidyverse"><i class="fa fa-check"></i><b>2.4.1</b> Introducing the ‘pipe’ in tidyverse</a></li>
<li class="chapter" data-level="2.4.2" data-path="tidyverse.html"><a href="tidyverse.html#select-in-tidyverse"><i class="fa fa-check"></i><b>2.4.2</b> select() in tidyverse</a></li>
<li class="chapter" data-level="2.4.3" data-path="tidyverse.html"><a href="tidyverse.html#a-warning-about-the-select-command"><i class="fa fa-check"></i><b>2.4.3</b> A warning about the select() command</a></li>
<li class="chapter" data-level="2.4.4" data-path="tidyverse.html"><a href="tidyverse.html#arrange-in-tidyverse"><i class="fa fa-check"></i><b>2.4.4</b> arrange() in tidyverse</a></li>
<li class="chapter" data-level="2.4.5" data-path="tidyverse.html"><a href="tidyverse.html#glimpse-in-tidyverse"><i class="fa fa-check"></i><b>2.4.5</b> glimpse() in tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tidyverse.html"><a href="tidyverse.html#review-of-this-chapters-commands-1"><i class="fa fa-check"></i><b>2.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>3</b> Graphing and describing variables</a>
<ul>
<li class="chapter" data-level="3.1" data-path="graphing.html"><a href="graphing.html#getting-started-tidyverse"><i class="fa fa-check"></i><b>3.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="graphing.html"><a href="graphing.html#start-graphing"><i class="fa fa-check"></i><b>3.2</b> Getting started with ggplot and graphing</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="graphing.html"><a href="graphing.html#bar-graph-nominal"><i class="fa fa-check"></i><b>3.2.1</b> Bar graphing a nominal variable</a></li>
<li class="chapter" data-level="3.2.2" data-path="graphing.html"><a href="graphing.html#remove-na"><i class="fa fa-check"></i><b>3.2.2</b> Removing the NA bar</a></li>
<li class="chapter" data-level="3.2.3" data-path="graphing.html"><a href="graphing.html#add-return"><i class="fa fa-check"></i><b>3.2.3</b> Adding a second line to a graph’s title</a></li>
<li class="chapter" data-level="3.2.4" data-path="graphing.html"><a href="graphing.html#saving-a-graph"><i class="fa fa-check"></i><b>3.2.4</b> Saving a graph</a></li>
<li class="chapter" data-level="3.2.5" data-path="graphing.html"><a href="graphing.html#bar-graph-ordinal"><i class="fa fa-check"></i><b>3.2.5</b> Bar graphing an ordinal variable</a></li>
<li class="chapter" data-level="3.2.6" data-path="graphing.html"><a href="graphing.html#what-to-do-about-overlapping-labels"><i class="fa fa-check"></i><b>3.2.6</b> What to do about overlapping labels</a></li>
<li class="chapter" data-level="3.2.7" data-path="graphing.html"><a href="graphing.html#histogram"><i class="fa fa-check"></i><b>3.2.7</b> Generating a histogram</a></li>
<li class="chapter" data-level="3.2.8" data-path="graphing.html"><a href="graphing.html#removing-scientific-notation-from-axes"><i class="fa fa-check"></i><b>3.2.8</b> Removing scientific notation from axes</a></li>
<li class="chapter" data-level="3.2.9" data-path="graphing.html"><a href="graphing.html#adjusting-bin-width-on-a-histogram"><i class="fa fa-check"></i><b>3.2.9</b> Adjusting bin width on a histogram</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion"><i class="fa fa-check"></i><b>3.3</b> Central tendancy and dispersion</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-nominal-variables"><i class="fa fa-check"></i><b>3.3.1</b> Central tendency and dispersion of nominal variables</a></li>
<li class="chapter" data-level="3.3.2" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-ordinal-variables"><i class="fa fa-check"></i><b>3.3.2</b> Central tendency and dispersion of ordinal variables</a></li>
<li class="chapter" data-level="3.3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion-of-interval-variables"><i class="fa fa-check"></i><b>3.3.3</b> Central tendancy and dispersion of interval variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="graphing.html"><a href="graphing.html#states-world"><i class="fa fa-check"></i><b>3.4</b> A note on using the states2025 and world2025</a></li>
<li class="chapter" data-level="3.5" data-path="graphing.html"><a href="graphing.html#review-of-this-chapters-commands-2"><i class="fa fa-check"></i><b>3.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="recoding.html"><a href="recoding.html"><i class="fa fa-check"></i><b>4</b> Recoding and comparing values of variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="recoding.html"><a href="recoding.html#getting-started-recoding"><i class="fa fa-check"></i><b>4.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="recoding.html"><a href="recoding.html#recode-nom"><i class="fa fa-check"></i><b>4.2</b> Recoding ordinal and nominal variables</a></li>
<li class="chapter" data-level="4.3" data-path="recoding.html"><a href="recoding.html#reverse-ord"><i class="fa fa-check"></i><b>4.3</b> Reversing the order of ordinal variables</a></li>
<li class="chapter" data-level="4.4" data-path="recoding.html"><a href="recoding.html#factor-as-numeric"><i class="fa fa-check"></i><b>4.4</b> Making ordinal variables numeric</a></li>
<li class="chapter" data-level="4.5" data-path="recoding.html"><a href="recoding.html#recode-dummy"><i class="fa fa-check"></i><b>4.5</b> Dealing with variables coded 0/1</a></li>
<li class="chapter" data-level="4.6" data-path="recoding.html"><a href="recoding.html#simp-int"><i class="fa fa-check"></i><b>4.6</b> Simplifying interval variables</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="recoding.html"><a href="recoding.html#cut-2"><i class="fa fa-check"></i><b>4.6.1</b> Simplifying interval variables using cut2()</a></li>
<li class="chapter" data-level="4.6.2" data-path="recoding.html"><a href="recoding.html#case-when"><i class="fa fa-check"></i><b>4.6.2</b> Simplifying interval variables with case_when</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="recoding.html"><a href="recoding.html#cross-tabs"><i class="fa fa-check"></i><b>4.7</b> Cross-tabulation tables</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="recoding.html"><a href="recoding.html#generating-cross-tabs"><i class="fa fa-check"></i><b>4.7.1</b> Generating cross-tabs</a></li>
<li class="chapter" data-level="4.7.2" data-path="recoding.html"><a href="recoding.html#adding-column-totals-to-cross-tabs"><i class="fa fa-check"></i><b>4.7.2</b> Adding column totals to cross-tabs</a></li>
<li class="chapter" data-level="4.7.3" data-path="recoding.html"><a href="recoding.html#column-percents"><i class="fa fa-check"></i><b>4.7.3</b> Adding column percents to cross-tabs</a></li>
<li class="chapter" data-level="4.7.4" data-path="recoding.html"><a href="recoding.html#export-crosstabs"><i class="fa fa-check"></i><b>4.7.4</b> Exporting cross-tabs for your word processor</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="recoding.html"><a href="recoding.html#mean-comparison-tables"><i class="fa fa-check"></i><b>4.8</b> Mean comparison tables</a></li>
<li class="chapter" data-level="4.9" data-path="recoding.html"><a href="recoding.html#review-of-this-chapters-commands-3"><i class="fa fa-check"></i><b>4.9</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html"><i class="fa fa-check"></i><b>5</b> Making controlled comparisons</a>
<ul>
<li class="chapter" data-level="5.1" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#getting-started-comparisons"><i class="fa fa-check"></i><b>5.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="5.2" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#stacked"><i class="fa fa-check"></i><b>5.2</b> Representing crosstabs with stacked bar graphs</a></li>
<li class="chapter" data-level="5.3" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#representing-mean-comparison-tables-with-boxplots"><i class="fa fa-check"></i><b>5.3</b> Representing mean comparison tables with boxplots</a></li>
<li class="chapter" data-level="5.4" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-crosstab"><i class="fa fa-check"></i><b>5.4</b> Adding a control to a crosstab</a></li>
<li class="chapter" data-level="5.5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-mean-comparison-table"><i class="fa fa-check"></i><b>5.5</b> Adding a control to a mean comparison table</a></li>
<li class="chapter" data-level="5.6" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#review-of-this-chapters-commands-4"><i class="fa fa-check"></i><b>5.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferences.html"><a href="inferences.html"><i class="fa fa-check"></i><b>6</b> Making inferences from sample means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferences.html"><a href="inferences.html#getting-started-inferences"><i class="fa fa-check"></i><b>6.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="6.2" data-path="inferences.html"><a href="inferences.html#constructing-a-confidence-interval-around-a-mean"><i class="fa fa-check"></i><b>6.2</b> Constructing a confidence interval around a mean</a></li>
<li class="chapter" data-level="6.3" data-path="inferences.html"><a href="inferences.html#ci-around-proportion"><i class="fa fa-check"></i><b>6.3</b> Constructing a confidence interval around a proportion</a></li>
<li class="chapter" data-level="6.4" data-path="inferences.html"><a href="inferences.html#ci-around-proportions"><i class="fa fa-check"></i><b>6.4</b> Constructing confidence intervals around several proportions at once</a></li>
<li class="chapter" data-level="6.5" data-path="inferences.html"><a href="inferences.html#t-test-ind-means"><i class="fa fa-check"></i><b>6.5</b> T-test of independent means</a></li>
<li class="chapter" data-level="6.6" data-path="inferences.html"><a href="inferences.html#caution-about-statistical-significance"><i class="fa fa-check"></i><b>6.6</b> Caution about “statistical significance”</a></li>
<li class="chapter" data-level="6.7" data-path="inferences.html"><a href="inferences.html#t-test-ind-props"><i class="fa fa-check"></i><b>6.7</b> T-test of independent proportions</a></li>
<li class="chapter" data-level="6.8" data-path="inferences.html"><a href="inferences.html#review-of-this-chapters-commands-5"><i class="fa fa-check"></i><b>6.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html"><i class="fa fa-check"></i><b>7</b> From chi-squared to somers’ d</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#getting-started-chi"><i class="fa fa-check"></i><b>7.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="7.2" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#chi-squared"><i class="fa fa-check"></i><b>7.2</b> Calculating chi-squared</a></li>
<li class="chapter" data-level="7.3" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#lambda"><i class="fa fa-check"></i><b>7.3</b> Lambda and the PREs</a></li>
<li class="chapter" data-level="7.4" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#cramers-v"><i class="fa fa-check"></i><b>7.4</b> Cramer’s V</a></li>
<li class="chapter" data-level="7.5" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#somers-d"><i class="fa fa-check"></i><b>7.5</b> Somers’ D</a></li>
<li class="chapter" data-level="7.6" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#review-of-this-chapters-commands-6"><i class="fa fa-check"></i><b>7.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="pearsons-r.html"><a href="pearsons-r.html"><i class="fa fa-check"></i><b>8</b> Pearson’s r and linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="pearsons-r.html"><a href="pearsons-r.html#getting-started-pearsons-r"><i class="fa fa-check"></i><b>8.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="8.2" data-path="pearsons-r.html"><a href="pearsons-r.html#pearsons-r-1"><i class="fa fa-check"></i><b>8.2</b> Pearson’s R</a></li>
<li class="chapter" data-level="8.3" data-path="pearsons-r.html"><a href="pearsons-r.html#scatterplot"><i class="fa fa-check"></i><b>8.3</b> The scatterplot</a></li>
<li class="chapter" data-level="8.4" data-path="pearsons-r.html"><a href="pearsons-r.html#bivariate-regression"><i class="fa fa-check"></i><b>8.4</b> Bivariate linear regression</a></li>
<li class="chapter" data-level="8.5" data-path="pearsons-r.html"><a href="pearsons-r.html#residuals"><i class="fa fa-check"></i><b>8.5</b> Residuals</a></li>
<li class="chapter" data-level="8.6" data-path="pearsons-r.html"><a href="pearsons-r.html#review-of-this-chapters-commands-7"><i class="fa fa-check"></i><b>8.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#getting-started-multiple-regression"><i class="fa fa-check"></i><b>9.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#multiple-regression"><i class="fa fa-check"></i><b>9.2</b> Multiple regression</a></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#residuals-in-multiple-regression"><i class="fa fa-check"></i><b>9.3</b> Residuals in multiple regression</a></li>
<li class="chapter" data-level="9.4" data-path="regression.html"><a href="regression.html#stargazer"><i class="fa fa-check"></i><b>9.4</b> Stargazer output</a></li>
<li class="chapter" data-level="9.5" data-path="regression.html"><a href="regression.html#dummy-variables-in-multiple-regression"><i class="fa fa-check"></i><b>9.5</b> Dummy variables in multiple regression</a></li>
<li class="chapter" data-level="9.6" data-path="regression.html"><a href="regression.html#ordinal-variables-in-regression-analysis"><i class="fa fa-check"></i><b>9.6</b> Ordinal variables in regression analysis</a></li>
<li class="chapter" data-level="9.7" data-path="regression.html"><a href="regression.html#graphing-multiple-regression"><i class="fa fa-check"></i><b>9.7</b> Graphing multiple regression</a></li>
<li class="chapter" data-level="9.8" data-path="regression.html"><a href="regression.html#review-of-this-chapters-commands-8"><i class="fa fa-check"></i><b>9.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="wild.html"><a href="wild.html"><i class="fa fa-check"></i><b>10</b> R in the wild</a>
<ul>
<li class="chapter" data-level="10.1" data-path="wild.html"><a href="wild.html#todays-lab-as-a-reference"><i class="fa fa-check"></i><b>10.1</b> Today’s lab as a reference</a></li>
<li class="chapter" data-level="10.2" data-path="wild.html"><a href="wild.html#importing-data-into-r"><i class="fa fa-check"></i><b>10.2</b> Importing data into R</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="wild.html"><a href="wild.html#importing-csv-files"><i class="fa fa-check"></i><b>10.2.1</b> Importing CSV files</a></li>
<li class="chapter" data-level="10.2.2" data-path="wild.html"><a href="wild.html#importing-excel-files"><i class="fa fa-check"></i><b>10.2.2</b> Importing Excel files</a></li>
<li class="chapter" data-level="10.2.3" data-path="wild.html"><a href="wild.html#importing-other-files"><i class="fa fa-check"></i><b>10.2.3</b> Importing other files</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="wild.html"><a href="wild.html#cleaning-data-in-r"><i class="fa fa-check"></i><b>10.3</b> Cleaning data in R</a></li>
<li class="chapter" data-level="10.4" data-path="wild.html"><a href="wild.html#resources"><i class="fa fa-check"></i><b>10.4</b> Online R resources</a></li>
<li class="chapter" data-level="10.5" data-path="wild.html"><a href="wild.html#the-last-command-how-to-get-help"><i class="fa fa-check"></i><b>10.5</b> The last command: how to get help</a></li>
<li class="chapter" data-level="10.6" data-path="wild.html"><a href="wild.html#the-strausz-method-for-improving-in-r"><i class="fa fa-check"></i><b>10.6</b> The Strausz method for improving in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chi-squared-etc" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> From chi-squared to somers’ d<a href="chi-squared-etc.html#chi-squared-etc" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="getting-started-chi" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Getting started with this chapter<a href="chi-squared-etc.html#getting-started-chi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To get started in today’s chapter, open the project that you made in lab 1. If you forgot how to do this, see the instructions in section <a href="tidyverse.html#exploring">2.2</a>.</p>
<p>Now, open a new script file and save it in your scripts folder as “chapter <a href="chi-squared-etc.html#chi-squared-etc">7</a> practice.” Copy and paste this onto the page (updating the text so that it is about you):</p>
<pre><code>####################################
# Your name
# 20093 Chapter 7, Practice exercises
# Date started : Date last modified
####################################

#libraries------------------------------------------
library(tidyverse)
library(Hmisc)        #the cut2 command helps us simplify interval variables
library(scales)       #this is useful when the labels on our axes overlap
library(tigerstats)   #colPerc can also be useful with crosstabs 
library(DescTools)    #this has tools to calculate Cramer&#39;s V, Lambda and Somers&#39; D</code></pre>
<p>Now select all the text on this page, run it, and save it.</p>
</div>
<div id="chi-squared" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Calculating chi-squared<a href="chi-squared-etc.html#chi-squared" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In chapter <a href="inferences.html#inferences">6</a>, we learned two tools to think about relationships between variables: a t-test of independent means and a t-test of independent proportions. These tests let us compare two groups and see whether their means or proportions differ in a statistically significant way. However, what if we want to compare more than two groups at the same time? And, in the case of proportions, what if we want to look at several different proportions at once? For example, the proportion of people that support, oppose and neither support nor oppose military aid to Ukraine?</p>
<p>In other words, to return to a concept from chapter <a href="recoding.html#recoding">4</a>, what if we wanted to look at a whole cross tabulation table (a crosstab) and decide whether the values that we observe are likely due to random sampling error, or due to a correlation at the population level?</p>
<p>The most basic way to do that is by calculating chi-squared. That statistic tells us whether the values of variables that we observe in a crosstab are so different from what we would expect to observe if there was no association between the variables at the population level that we can conclude that there likely is such a relationship. For this example, we will think about the relationship between the dominant religion of a country and percent of legislators that are women. We will think through that question with help from our world2025 dataframe, using the “religion” variable and the “femLeg” variable.</p>
<p>Before we generate our crosstab, we first have to deal with an issue: the femLeg variable is interval. If we generate a crosstab with that variable as the DV, that crosstab will have one row for each value of that variable, which would give us 160 different rows.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> We don’t want that! Instead, let’s use the technique that we learned in section <a href="recoding.html#cut-2">4.6.1</a> and simplify that variable into a new variable called “femLeg3.” First, we will use the cut2 command to generate a variable with three groups:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="chi-squared-etc.html#cb161-1" tabindex="-1"></a>world2025<span class="sc">$</span>femLeg3<span class="ot">&lt;-</span><span class="fu">cut2</span>(world2025<span class="sc">$</span>femLeg, <span class="at">g=</span><span class="dv">3</span>)</span></code></pre></div>
<p>Next, we can look at the levels of our new ordinal variable, like this:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="chi-squared-etc.html#cb162-1" tabindex="-1"></a><span class="fu">levels</span>(world2025<span class="sc">$</span>femLeg3)</span></code></pre></div>
<pre><code>## [1] &quot;[ 0.0,20.4)&quot; &quot;[20.4,32.2)&quot; &quot;[32.2,61.2]&quot;</code></pre>
<p>Finally, we can rename those levels, like this:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="chi-squared-etc.html#cb164-1" tabindex="-1"></a><span class="fu">levels</span>(world2025<span class="sc">$</span>femLeg3)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">&quot;fewer&quot;</span>,<span class="st">&quot;typical&quot;</span>,<span class="st">&quot;many&quot;</span>)</span></code></pre></div>
<p>Now, we can generate a crosstab, with this command (remember when generating a crosstab we put our dependent variable first):</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="chi-squared-etc.html#cb165-1" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025))</span></code></pre></div>
<pre><code>##          religion
## femLeg3   Eastern Hindu Jewish Muslim Orthodox Other Protestant Roman Cath Sum
##   fewer         9     1      0     26        4     5          7          6  58
##   typical       4     0      1     14        3     4          5         22  53
##   many          1     1      0      6        5     2         14         23  52
##   Sum          14     2      1     46       12    11         26         51 163</code></pre>
<p>This crosstab gives us raw numbers, which are interesting to look at. It also foreshadows a potential limitation to our conclusions. Because we only have one predominantly Jewish state (Israel) and two predominantly Hindu states (Nepal and Mauritius) in our sample, we will be attempting to generalize about those two kinds of states from a tiny sample. We discuss that issue more below. To better interpret this crosstab, we need to look at column percents, which we can do with this command:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="chi-squared-etc.html#cb167-1" tabindex="-1"></a><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025))</span></code></pre></div>
<pre><code>##          religion
## femLeg3   Eastern Hindu Jewish Muslim Orthodox  Other Protestant Roman Cath
##   fewer     64.29    50      0  56.52    33.33  45.45      26.92      11.76
##   typical   28.57     0    100  30.43    25.00  36.36      19.23      43.14
##   many       7.14    50      0  13.04    41.67  18.18      53.85      45.10
##   Total    100.00   100    100 100.00   100.00 100.00     100.00     100.00</code></pre>
<p>Take a look at that table. You can see that there are some pretty noticeable differences in female representation across states with different major religions. For example, the religion with the largest percentage of states with many women in their legislatures is Protestantism, with 53.85%, followed by Roman Catholicism, with 45.1%. To help us visualize these differences, we can generate a stacked bar graph using the technique that we learned in section <a href="making-controlled-comparisons.html#stacked">5.2</a>:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="chi-squared-etc.html#cb169-1" tabindex="-1"></a>plotting.data<span class="ot">&lt;-</span>world2025 <span class="sc">%&gt;%</span></span>
<span id="cb169-2"><a href="chi-squared-etc.html#cb169-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(religion)<span class="sc">&amp;!</span><span class="fu">is.na</span>(femLeg3)) <span class="sc">%&gt;%</span> </span>
<span id="cb169-3"><a href="chi-squared-etc.html#cb169-3" tabindex="-1"></a>  <span class="fu">group_by</span>(religion, femLeg3) <span class="sc">%&gt;%</span> </span>
<span id="cb169-4"><a href="chi-squared-etc.html#cb169-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb169-5"><a href="chi-squared-etc.html#cb169-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb169-6"><a href="chi-squared-etc.html#cb169-6" tabindex="-1"></a></span>
<span id="cb169-7"><a href="chi-squared-etc.html#cb169-7" tabindex="-1"></a><span class="fu">ggplot</span>(plotting.data, <span class="fu">aes</span>(<span class="at">x =</span> religion, <span class="at">y =</span> freq, <span class="at">fill=</span>femLeg3)) <span class="sc">+</span></span>
<span id="cb169-8"><a href="chi-squared-etc.html#cb169-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="sc">+</span></span>
<span id="cb169-9"><a href="chi-squared-etc.html#cb169-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>percent)<span class="sc">+</span></span>
<span id="cb169-10"><a href="chi-squared-etc.html#cb169-10" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>))<span class="sc">+</span> </span>
<span id="cb169-11"><a href="chi-squared-etc.html#cb169-11" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name=</span><span class="st">&quot;Women in legislature&quot;</span>)<span class="sc">+</span> </span>
<span id="cb169-12"><a href="chi-squared-etc.html#cb169-12" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Countries&#39; major religion and women in legislature&quot;</span>)<span class="sc">+</span></span>
<span id="cb169-13"><a href="chi-squared-etc.html#cb169-13" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>)<span class="sc">+</span></span>
<span id="cb169-14"><a href="chi-squared-etc.html#cb169-14" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Clearly, there are differences in the distribution of women in legislatures in countries with different major religions. But, are these differences statistically significant? To test that, we can ask R to calculate the chi-squared value that is associated with this relationship. We can use the chisq.test() command, and in the parenthesis we can put the command that generates crosstab that we want to run this test on. <em>Note: be careful to use the chisq.test() command on the command for a crosstab with actual values and not percents, or the test will not be accurate.</em></p>
<p>Here is how we would generate a chi-squared value for the relationship between dominant religion of a country and the percent of women in the legislature:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="chi-squared-etc.html#cb170-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025))</span></code></pre></div>
<pre><code>## Warning in chisq.test(xtabs(~femLeg3 + religion, data = world2025)):
## Chi-squared approximation may be incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  xtabs(~femLeg3 + religion, data = world2025)
## X-squared = 40.057, df = 14, p-value = 0.00025</code></pre>
<p>Look at what R tells us in this output (the text just above this passage, beginning with <code>##  Pearson's Chi-squared test</code>). First, R reports that it will be giving us the results of a Pearson’s Chi-squared test. Second, it repeats the command that we entered. Third, it reports the value for chi-squared (which it writes as X-squared), tells us our degrees of freedom (calculated by (number of rows-1)*(number of columns-1)) and reports our p-value. Lower p values mean that the relationship that we are observing is more likely to be statistically significant (i.e. not due to random sampling error). In this case, our p-value is very low: .00025, which means that, according to the chi-squared test, this relationship is statistically significant (because .00025 is lower than .05, our conventional benchmark).</p>
<p>However, look at warning at the top: R is warning us that this estimate may be wrong. Why? This has to do with the expected values of the cells in our crosstab. Let’s take another look at the crosstab that we generated earlier:</p>
<pre><code>##          religion
## femLeg3   Eastern Hindu Jewish Muslim Orthodox Other Protestant Roman Cath Sum
##   fewer         9     1      0     26        4     5          7          6  58
##   typical       4     0      1     14        3     4          5         22  53
##   many          1     1      0      6        5     2         14         23  52
##   Sum          14     2      1     46       12    11         26         51 163</code></pre>
<p>Look at top cell in the “Hindu” column: countries where Hinduism is dominant that have fewer women in their legislatures. There is only one country in that category. If there were no relationship at all between a country’s religion, we would expect that cell to be the row total*the column total/the total number of cases in the table. So, (58*2)/163, which is .712<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a>. As a general rule, if some cells in a crosstab have an expected value of less than 5, value of the chi-squared test will be artificially high, and we will be more likely to make Type I error (rejecting a true null hypothesis). In this case, we can actually look at the expected values of all of our cells with this command:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="chi-squared-etc.html#cb174-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025))<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>## Warning in chisq.test(xtabs(~femLeg3 + religion, data = world2025)):
## Chi-squared approximation may be incorrect</code></pre>
<pre><code>##          religion
## femLeg3    Eastern     Hindu    Jewish   Muslim Orthodox    Other Protestant
##   fewer   4.981595 0.7116564 0.3558282 16.36810 4.269939 3.914110   9.251534
##   typical 4.552147 0.6503067 0.3251534 14.95706 3.901840 3.576687   8.453988
##   many    4.466258 0.6380368 0.3190184 14.67485 3.828221 3.509202   8.294479
##          religion
## femLeg3   Roman Cath
##   fewer     18.14724
##   typical   16.58282
##   many      16.26994</code></pre>
<p>Looking over this output, we can see that we have many cells with expected values below 5, and thus our estimated chi-squared is less helpful.</p>
</div>
<div id="lambda" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Lambda and the PREs<a href="chi-squared-etc.html#lambda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One way to address the deficiency in chi-squared—that chi-squared is less accurate when the expected values of some of our cells is quite small—is with Lambda. Lambda is the first of several Proportional Reduction in Error (PRE) statistics that we will be learning about in class.</p>
<p>PRE statistics produce a value between 0 and 1 or between 0 and |1| (in the case of PRE statistics that let us look at the direction of relationships). These statistics are useful in interpreting both the significance and strength of relationships. A PRE statistic with a value of 0 means that knowing the independent value has no impact on our ability to correctly predict the value of the dependent variable, while a PRE statistic with a value of 1 (or -1, in the case of a negative relationship) means that knowing our independent variable will allow us to perfectly predict the value of our dependent variable (these kinds of perfect relationships do not exist in actual political science). A PRE statistic of .35, for example, tells us that knowing our independent variable improves our ability to guess the dependent variable by a probability of .35 (or 35%) compared with how good our guess would be if we did not know the independent variable.</p>
<p>Here is a general rule of thumb when interpreting PRE-statistics on social science data <span class="citation">(this is based on <a href="#ref-pollock-edwards">Pollock and Edwards 2019, 225</a>)</span>:</p>
<pre><code>## Warning: &#39;xfun::attr()&#39; is deprecated.
## Use &#39;xfun::attr2()&#39; instead.
## See help(&quot;Deprecated&quot;)
## Warning: &#39;xfun::attr()&#39; is deprecated.
## Use &#39;xfun::attr2()&#39; instead.
## See help(&quot;Deprecated&quot;)</code></pre>
<table>
<thead>
<tr>
<th align="left">Range of values</th>
<th align="left">Strength of relationship</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">0 and .1</td>
<td align="left">Weak relationship</td>
</tr>
<tr>
<td align="left">0 and -.1</td>
<td align="left">Weak relationship</td>
</tr>
<tr>
<td align="left">.1 and .2</td>
<td align="left">Moderate relationship</td>
</tr>
<tr>
<td align="left">-.1 and -.2</td>
<td align="left">Moderate relationship</td>
</tr>
<tr>
<td align="left">.2 and .3</td>
<td align="left">Moderately strong relationship</td>
</tr>
<tr>
<td align="left">-.2 and -.3</td>
<td align="left">Moderately strong relationship</td>
</tr>
<tr>
<td align="left">Above .3 or below -.3</td>
<td align="left">Strong relationship</td>
</tr>
</tbody>
</table>
<p>We can ask R to calculate Lambda in a way similar to the way that we had R calculate chi-square:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="chi-squared-etc.html#cb178-1" tabindex="-1"></a><span class="fu">Lambda</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025))</span></code></pre></div>
<pre><code>## [1] 0.2119816</code></pre>
<p>In other words, R is telling us that knowing the religion of a country improves the probability that we will correctly guess the level of economic equality in that country by about .21 (or 21%). That is a moderately strong relationship. However, that statistic alone does not tell us about statistical significance (or the chance that the relationship that we observe is due to random sampling error). To fix that, we can add “conf.level=.95” to our command from above (we could also set the confidence level to .99, or .9, or something else, but .95 is the standard in political science). This is our new command:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="chi-squared-etc.html#cb180-1" tabindex="-1"></a><span class="fu">Lambda</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025), <span class="at">conf.level=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##    lambda    lwr.ci    upr.ci 
## 0.2119816 0.1281852 0.2957780</code></pre>
<p>While this output does not directly report a significance level, unlike the t-tests and chi-squared tests that we ran earlier, the confidence interval that it reports is extremely helpful. This tells is that there is a 95% chance that the true value of Lambda is somewhere between .128 (which would be a moderate relationship) and .296 (which would be a moderately strong relationship). In other words, we are pretty confident that this relationship is moderate or moderately strong. <strong>If this reported interval had included 0, we would have concluded that the relationship was not statistically significant.</strong></p>
</div>
<div id="cramers-v" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Cramer’s V<a href="chi-squared-etc.html#cramers-v" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Lambda sometimes underestimates the strength of a relationship when there is little variation between the overall mode of a sample and the modes of each of our groups. In that case, we can use Cramer’s V instead. Or, given how easy it is to ask R to calculate these statistics, we can actually ask R to calculate chi-squared, lambda, and Cramer’s V, and if they provide similar information, that is a good sign that there might be something to our hypothesis.</p>
<p>Unlike Lambda, Cramer’s V is not a PRE statistic, which means that we can’t interpret it in terms of improved probability of guessing our dependent variable with knowledge of our independent variable. However, like Lambda, it reports a statistic between 0 and 1, and higher values mean that we have a stronger relationship. We can also use the same ” conf.level=.95” qualifier to get a confidence interval around our estimate, like this:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="chi-squared-etc.html#cb182-1" tabindex="-1"></a><span class="fu">CramerV</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>femLeg3<span class="sc">+</span>religion, <span class="at">data=</span>world2025), <span class="at">conf.level=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##  Cramer V    lwr.ci    upr.ci 
## 0.3505328 0.1606482 0.4060984</code></pre>
<p>Seeing this confidence interval with a lower bound nowhere near zero gives us additional evidence that there is likely a relationship between religion and economic equality at the population level.</p>
</div>
<div id="somers-d" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Somers’ D<a href="chi-squared-etc.html#somers-d" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>All of the measures of association that we have looked at so far have been useful for thinking about the relationship between two ordinal or nominal variables. But if we have two ordinal variables, we can also start to think about the direction of our relationship. In other words, we can go beyond asking whether knowing our independent variable helps us predict our dependent variable and ask whether an increase in our independent variable is associated with an increase (or decrease) in our dependent variable.</p>
<p>This kind of question does not make sense when discussing nominal variables, such as marital status. In other words, it does not make sense to ask whether marital status “increasing” leads to income increasing, because there is no order in which the values for the marital status variable (divorced, married, never married, separated, and widowed) must be listed.</p>
<p>For this example, let’s return to the relationship between ideas about whether America is better than other countries and support for aid to Ukraine that we looked at in section <a href="inferences.html#t-test-ind-props">6.7</a>.</p>
<p>My theory is that people that believe that America is better than other countries will tend to support military aid to Ukraine, because they will conceive of that kind of aid as a way to spread American values abroad (a democracy fighting off invasion from an autocracy). Before we can do our statistical tests of this theory, we can take a look the data in graphics and crosstabs to see whether the data seems to support our theory.</p>
<p>We can use the following two commands to generate a crosstab and a table of the columns percentages (notice that I put the dependent variable, armUkraine, first in these commands):</p>
<pre><code>xtabs(~armUkraine+natPride, data=anes2024)
colPerc(xtabs(~armUkraine+natPride, data=anes2024))</code></pre>
<p>One tip before we move on: R is almost always willing to create an object so that you don’t have to keep typing the same things over and over. So, in this case, you can make your crosstab an object called xt like this:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="chi-squared-etc.html#cb185-1" tabindex="-1"></a>xt<span class="ot">&lt;-</span><span class="fu">xtabs</span>(<span class="sc">~</span>armUkraine<span class="sc">+</span>natPride, <span class="at">data=</span>anes2024)</span></code></pre></div>
<p>Then, to see what that table looks like, you can run this line of code:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="chi-squared-etc.html#cb186-1" tabindex="-1"></a>xt</span></code></pre></div>
<pre><code>##                  natPride
## armUkraine        a lot better somewhat better the same somewhat worse
##   favor strongly           387             341      299            166
##   favor                    239             202      200            129
##   favor weakly              51              72       61             36
##   neither                  276             297      327            187
##   oppose weakly             33              30       32             33
##   oppose                   104             101       93             52
##   oppose strongly          187             117      107             98
##                  natPride
## armUkraine        a lot worse
##   favor strongly           88
##   favor                    67
##   favor weakly             16
##   neither                 112
##   oppose weakly             9
##   oppose                   34
##   oppose strongly          80</code></pre>
<p>After that, to generate the table with column percents, you can go like this:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="chi-squared-etc.html#cb188-1" tabindex="-1"></a><span class="fu">colPerc</span>(xt)</span></code></pre></div>
<pre><code>##                  natPride
## armUkraine        a lot better somewhat better the same somewhat worse
##   favor strongly         30.31           29.40    26.72          23.68
##   favor                  18.72           17.41    17.87          18.40
##   favor weakly            3.99            6.21     5.45           5.14
##   neither                21.61           25.60    29.22          26.68
##   oppose weakly           2.58            2.59     2.86           4.71
##   oppose                  8.14            8.71     8.31           7.42
##   oppose strongly        14.64           10.09     9.56          13.98
##   Total                 100.00          100.00   100.00         100.00
##                  natPride
## armUkraine        a lot worse
##   favor strongly        21.67
##   favor                 16.50
##   favor weakly           3.94
##   neither               27.59
##   oppose weakly          2.22
##   oppose                 8.37
##   oppose strongly       19.70
##   Total                100.00</code></pre>
<p>Let’s look at the second table, with the percents. The first column in that table tells us that, among those who believe that the US is a lot better than other countries, 30.31% strongly favor military aid to Ukraine, and 14.64% oppose military aide to Ukraine strongly. However, the last column shows us thatm among those to think that the US is a lot worst than other countries, 21.67% strongly favor military aid to Ukraine, and 19.7% oppose. That seems like a piece of evidence for our theory!</p>
<p>We have a number of choices for how to represent this relationship graphically. Since we generated a bar graph with error bars in of this relationship in section <a href="inferences.html#t-test-ind-props">6.7</a>, for this section let’s generate stacked bar graph.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="chi-squared-etc.html#cb190-1" tabindex="-1"></a>plotting.data<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span></span>
<span id="cb190-2"><a href="chi-squared-etc.html#cb190-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(armUkraine)<span class="sc">&amp;!</span><span class="fu">is.na</span>(natPride)) <span class="sc">%&gt;%</span> </span>
<span id="cb190-3"><a href="chi-squared-etc.html#cb190-3" tabindex="-1"></a>  <span class="fu">group_by</span>(natPride, armUkraine) <span class="sc">%&gt;%</span> </span>
<span id="cb190-4"><a href="chi-squared-etc.html#cb190-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb190-5"><a href="chi-squared-etc.html#cb190-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb190-6"><a href="chi-squared-etc.html#cb190-6" tabindex="-1"></a></span>
<span id="cb190-7"><a href="chi-squared-etc.html#cb190-7" tabindex="-1"></a><span class="fu">ggplot</span>(plotting.data, <span class="fu">aes</span>(<span class="at">x =</span> natPride, <span class="at">y =</span> freq, <span class="at">fill=</span>armUkraine)) <span class="sc">+</span></span>
<span id="cb190-8"><a href="chi-squared-etc.html#cb190-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="sc">+</span></span>
<span id="cb190-9"><a href="chi-squared-etc.html#cb190-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>percent)<span class="sc">+</span></span>
<span id="cb190-10"><a href="chi-squared-etc.html#cb190-10" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>))<span class="sc">+</span> <span class="co">#this line is in here because without it the x-axis labels overlap. You can remove it if that isn’t a problem </span></span>
<span id="cb190-11"><a href="chi-squared-etc.html#cb190-11" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name=</span><span class="st">&quot;Arms to Ukraine&quot;</span>)<span class="sc">+</span> <span class="co">#this color palate is made to be readable for colorblind people</span></span>
<span id="cb190-12"><a href="chi-squared-etc.html#cb190-12" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;National Pride and Aid to Ukraine, 2024&quot;</span>)<span class="sc">+</span></span>
<span id="cb190-13"><a href="chi-squared-etc.html#cb190-13" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Is the US better than other countries?&quot;</span>)<span class="sc">+</span></span>
<span id="cb190-14"><a href="chi-squared-etc.html#cb190-14" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-103-1.png" width="672" /></p>
<p>Notice that the bars are going in the way our theory predicted – people that think America is better than other countries also seem to be more supportive of errors to Ukraine. But are these differences larger than we would expect to see from random sampling error?</p>
<p>First, if you didn’t generate the crosstab object before, you can do that now like this:</p>
<pre><code>xt&lt;-xtabs(~armUkraine+natPride, data=anes2024)</code></pre>
<p>Now you can simply execute these three commands:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="chi-squared-etc.html#cb192-1" tabindex="-1"></a><span class="fu">chisq.test</span>(xt)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  xt
## X-squared = 82.713, df = 24, p-value = 2.236e-08</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="chi-squared-etc.html#cb194-1" tabindex="-1"></a><span class="fu">Lambda</span>(xt, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##     lambda     lwr.ci     upr.ci 
## 0.02142435 0.00690347 0.03594523</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="chi-squared-etc.html#cb196-1" tabindex="-1"></a><span class="fu">CramerV</span>(xt, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##   Cramer V     lwr.ci     upr.ci 
## 0.06659213 0.04053637 0.07202800</code></pre>
<p>These three tests all show a statistically significant relationship. The statistics that we just calculated let us discuss the strength (in the case of Lambda) and significance (in the case of Cramer’s V and chi-squared) of the relationship that we are interested in, but how about the direction? To examine the direction of a relationship between two ordinal variables, we can use a Somers’ D test. Somers D is a Proportional Reduction in Error (PRE) statistic like Lambda. Unlike Lambda, however, which ranges from 0 to 1, Somers’ D can range from 0 to 1 OR -1. A perfect negative relationship, where knowledge of the independent variable lets us guess the value of the dependent variable with absolute certainty, would generate a Somers’ D score of -1, while a perfect positive relationship would generate a Somers’ D score of 1. A Somers’ D score of 0 means that knowing the independent variable gives us no insight at all in predicting the dependent variable.</p>
<p>Before we run Somers’ D, we need to see whether our hypothesis is predicting a positive or a negative relationship. What does it mean to “increase” or “decrease” on those two variables? For this, we can use the levels() command, like this:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="chi-squared-etc.html#cb198-1" tabindex="-1"></a><span class="fu">levels</span>(anes2024<span class="sc">$</span>natPride)</span></code></pre></div>
<pre><code>## [1] &quot;a lot better&quot;    &quot;somewhat better&quot; &quot;the same&quot;        &quot;somewhat worse&quot; 
## [5] &quot;a lot worse&quot;</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="chi-squared-etc.html#cb200-1" tabindex="-1"></a><span class="fu">levels</span>(anes2024<span class="sc">$</span>armUkraine)</span></code></pre></div>
<pre><code>## [1] &quot;favor strongly&quot;  &quot;favor&quot;           &quot;favor weakly&quot;    &quot;neither&quot;        
## [5] &quot;oppose weakly&quot;   &quot;oppose&quot;          &quot;oppose strongly&quot;</code></pre>
<p>The levels() command only works with ordered factors (which is how R treats ordinal variables), and the output lists the scores of the variable from low to high. So, the lowest value on natPride mean that the respondent thinks that the US is “a lot better” than other countries, and the highest means that the respondent thinks that the US is “a lot worse” than other countries. Increasing values means less national pride. With “armUkraine”, the lowest value means that the respondent “favors strongly” arming Ukraine, and the highest value means that the respondent “opposed strongly” arming Ukraine. So increasing values mean less support for arming Ukraine. Since our hypothesis is that Americans with more national pride will be more likely to support arming Ukraine, we hypothesize a positive relationship between those two variables.</p>
<p>We run Somers’ D just like how we ran Cramer’s V, Lambda, and chi-squared, above:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="chi-squared-etc.html#cb202-1" tabindex="-1"></a><span class="fu">SomersDelta</span>(xt, <span class="at">conf.level=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##     somers     lwr.ci     upr.ci 
## 0.04664520 0.02246288 0.07082751</code></pre>
<p>This is telling us that there is a .95 probability that Somer’s D at the population level is between .022 and .071. In other words, there is a positive, weak, and statistically significant relationship between national pride and views on arming Ukraine. The relationship is in the direction that our hypothesis predicted, and it is statistically significant, but the weakness of the relationship means that we would only reduce our error in guessing views on Ukraine a small amount (about 4.66%) if we knew how much national pride someone had.</p>
<p>One note: Somers’ D is an asymmetric test, which means that it gives different results when you treat one of your two variables as independent than when you treat that same variable as dependent. <strong>So, be careful to list your dependent variable first when setting up your test.</strong></p>
</div>
<div id="review-of-this-chapters-commands-6" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Review of this chapter’s commands<a href="chi-squared-etc.html#review-of-this-chapters-commands-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## Warning: &#39;xfun::attr()&#39; is deprecated.
## Use &#39;xfun::attr2()&#39; instead.
## See help(&quot;Deprecated&quot;)
## Warning: &#39;xfun::attr()&#39; is deprecated.
## Use &#39;xfun::attr2()&#39; instead.
## See help(&quot;Deprecated&quot;)</code></pre>
<table>
<colgroup>
<col width="5%" />
<col width="91%" />
<col width="3%" />
</colgroup>
<thead>
<tr>
<th align="left">Command</th>
<th align="left">Purpose</th>
<th align="left">Library</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">chisq.test()</td>
<td align="left">Runs a chi-squared test on a pair of variables. In this class we use it on crosstabs that we generate with the xtabs() command, but you can also use it on a table that you generate with other commands or on a pair of variables that you define with a $.</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">Lambda()</td>
<td align="left">Runs a Cramer’s V test (a test of the relationship between two nominal or ordinal variables) on a pair of variables. In this class we use it on crosstabs that we generate with the xtabs() command.</td>
<td align="left">DescTools</td>
</tr>
<tr>
<td align="left">CramerV()</td>
<td align="left">Runs a Lambda test (a PRE test of the relationship between two nominal or ordinal variables) on a pair of variables. In this class we use it on crosstabs that we generate with the xtabs() command.</td>
<td align="left">DescTools</td>
</tr>
<tr>
<td align="left">SomersDelta()</td>
<td align="left">Runs a Somers’ D test (a PRE test of the relationship between two ordinal variables) on a pair of variables. In this class we use it on crosstabs that we generate with the xtabs() command.</td>
<td align="left">DescTools</td>
</tr>
</tbody>
</table>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-pollock-edwards" class="csl-entry">
Pollock, Philip H, and Barry C Edwards. 2019. <em>The Essentials of Political Analysis</em>. Book. 6th ed. Sage.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="6">
<li id="fn6"><p>To see where I got the number 160 from, you can use this code, which asks R to count the number of unique values of the femLeg variable <code>length(unique(world2025$femLeg))</code><a href="chi-squared-etc.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>We can make R do this math for us by entering this command in the Console: <code>(58*2)/163</code><a href="chi-squared-etc.html#fnref7" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inferences.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="pearsons-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/07-chi.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
