<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Making controlled comparisons | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</title>
  <meta name="description" content="This is the preface of the workbook" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Making controlled comparisons | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the preface of the workbook" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Making controlled comparisons | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  
  <meta name="twitter:description" content="This is the preface of the workbook" />
  

<meta name="author" content="Michael Strausz" />


<meta name="date" content="2025-09-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="recoding.html"/>
<link rel="next" href="inferences.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Are You Ready for R?</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="whats-new-in-version-3.html"><a href="whats-new-in-version-3.html"><i class="fa fa-check"></i>What’s new in version 3.0?</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#why-r"><i class="fa fa-check"></i><b>1.1</b> Why R?</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#class-project"><i class="fa fa-check"></i><b>1.2</b> Create a project for this class</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#add-files"><i class="fa fa-check"></i><b>1.3</b> Add the course files to your project</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#using-the-console"><i class="fa fa-check"></i><b>1.4</b> Using the Console</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="getting-started.html"><a href="getting-started.html#rules-about-naming-objects"><i class="fa fa-check"></i><b>1.4.1</b> Rules about naming objects</a></li>
<li class="chapter" data-level="1.4.2" data-path="getting-started.html"><a href="getting-started.html#common-practices-when-naming-objects"><i class="fa fa-check"></i><b>1.4.2</b> Common practices when naming objects</a></li>
<li class="chapter" data-level="1.4.3" data-path="getting-started.html"><a href="getting-started.html#about-vectors"><i class="fa fa-check"></i><b>1.4.3</b> About vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#first-script"><i class="fa fa-check"></i><b>1.5</b> Writing your first R script</a></li>
<li class="chapter" data-level="1.6" data-path="getting-started.html"><a href="getting-started.html#wont-load"><i class="fa fa-check"></i><b>1.6</b> What do to if the “load” command doesn’t load the dataframe</a></li>
<li class="chapter" data-level="1.7" data-path="getting-started.html"><a href="getting-started.html#review-of-this-chapters-commands"><i class="fa fa-check"></i><b>1.7</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>2</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tidyverse.html"><a href="tidyverse.html#install-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Installing packages</a></li>
<li class="chapter" data-level="2.2" data-path="tidyverse.html"><a href="tidyverse.html#exploring"><i class="fa fa-check"></i><b>2.2</b> Exploring dataframes</a></li>
<li class="chapter" data-level="2.3" data-path="tidyverse.html"><a href="tidyverse.html#org-script"><i class="fa fa-check"></i><b>2.3</b> Organizing your scripts</a></li>
<li class="chapter" data-level="2.4" data-path="tidyverse.html"><a href="tidyverse.html#welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>2.4</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="tidyverse.html"><a href="tidyverse.html#introducing-the-pipe-in-tidyverse"><i class="fa fa-check"></i><b>2.4.1</b> Introducing the ‘pipe’ in tidyverse</a></li>
<li class="chapter" data-level="2.4.2" data-path="tidyverse.html"><a href="tidyverse.html#select-in-tidyverse"><i class="fa fa-check"></i><b>2.4.2</b> select() in tidyverse</a></li>
<li class="chapter" data-level="2.4.3" data-path="tidyverse.html"><a href="tidyverse.html#a-warning-about-the-select-command"><i class="fa fa-check"></i><b>2.4.3</b> A warning about the select() command</a></li>
<li class="chapter" data-level="2.4.4" data-path="tidyverse.html"><a href="tidyverse.html#arrange-in-tidyverse"><i class="fa fa-check"></i><b>2.4.4</b> arrange() in tidyverse</a></li>
<li class="chapter" data-level="2.4.5" data-path="tidyverse.html"><a href="tidyverse.html#glimpse-in-tidyverse"><i class="fa fa-check"></i><b>2.4.5</b> glimpse() in tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tidyverse.html"><a href="tidyverse.html#review-of-this-chapters-commands-1"><i class="fa fa-check"></i><b>2.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>3</b> Graphing and describing variables</a>
<ul>
<li class="chapter" data-level="3.1" data-path="graphing.html"><a href="graphing.html#getting-started-tidyverse"><i class="fa fa-check"></i><b>3.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="graphing.html"><a href="graphing.html#start-graphing"><i class="fa fa-check"></i><b>3.2</b> Getting started with ggplot and graphing</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="graphing.html"><a href="graphing.html#bar-graph-nominal"><i class="fa fa-check"></i><b>3.2.1</b> Bar graphing a nominal variable</a></li>
<li class="chapter" data-level="3.2.2" data-path="graphing.html"><a href="graphing.html#remove-na"><i class="fa fa-check"></i><b>3.2.2</b> Removing the NA bar</a></li>
<li class="chapter" data-level="3.2.3" data-path="graphing.html"><a href="graphing.html#add-return"><i class="fa fa-check"></i><b>3.2.3</b> Adding a second line to a graph’s title</a></li>
<li class="chapter" data-level="3.2.4" data-path="graphing.html"><a href="graphing.html#saving-a-graph"><i class="fa fa-check"></i><b>3.2.4</b> Saving a graph</a></li>
<li class="chapter" data-level="3.2.5" data-path="graphing.html"><a href="graphing.html#bar-graph-ordinal"><i class="fa fa-check"></i><b>3.2.5</b> Bar graphing an ordinal variable</a></li>
<li class="chapter" data-level="3.2.6" data-path="graphing.html"><a href="graphing.html#what-to-do-about-overlapping-labels"><i class="fa fa-check"></i><b>3.2.6</b> What to do about overlapping labels</a></li>
<li class="chapter" data-level="3.2.7" data-path="graphing.html"><a href="graphing.html#histogram"><i class="fa fa-check"></i><b>3.2.7</b> Generating a histogram</a></li>
<li class="chapter" data-level="3.2.8" data-path="graphing.html"><a href="graphing.html#removing-scientific-notation-from-axes"><i class="fa fa-check"></i><b>3.2.8</b> Removing scientific notation from axes</a></li>
<li class="chapter" data-level="3.2.9" data-path="graphing.html"><a href="graphing.html#adjusting-bin-width-on-a-histogram"><i class="fa fa-check"></i><b>3.2.9</b> Adjusting bin width on a histogram</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion"><i class="fa fa-check"></i><b>3.3</b> Central tendancy and dispersion</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-nominal-variables"><i class="fa fa-check"></i><b>3.3.1</b> Central tendency and dispersion of nominal variables</a></li>
<li class="chapter" data-level="3.3.2" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-ordinal-variables"><i class="fa fa-check"></i><b>3.3.2</b> Central tendency and dispersion of ordinal variables</a></li>
<li class="chapter" data-level="3.3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion-of-interval-variables"><i class="fa fa-check"></i><b>3.3.3</b> Central tendancy and dispersion of interval variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="graphing.html"><a href="graphing.html#states-world"><i class="fa fa-check"></i><b>3.4</b> A note on using the states2025 and world2025</a></li>
<li class="chapter" data-level="3.5" data-path="graphing.html"><a href="graphing.html#review-of-this-chapters-commands-2"><i class="fa fa-check"></i><b>3.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="recoding.html"><a href="recoding.html"><i class="fa fa-check"></i><b>4</b> Recoding and comparing values of variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="recoding.html"><a href="recoding.html#getting-started-recoding"><i class="fa fa-check"></i><b>4.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="recoding.html"><a href="recoding.html#recode-nom"><i class="fa fa-check"></i><b>4.2</b> Recoding ordinal and nominal variables</a></li>
<li class="chapter" data-level="4.3" data-path="recoding.html"><a href="recoding.html#reverse-ord"><i class="fa fa-check"></i><b>4.3</b> Reversing the order of ordinal variables</a></li>
<li class="chapter" data-level="4.4" data-path="recoding.html"><a href="recoding.html#factor-as-numeric"><i class="fa fa-check"></i><b>4.4</b> Making ordinal variables numeric</a></li>
<li class="chapter" data-level="4.5" data-path="recoding.html"><a href="recoding.html#recode-dummy"><i class="fa fa-check"></i><b>4.5</b> Dealing with variables coded 0/1</a></li>
<li class="chapter" data-level="4.6" data-path="recoding.html"><a href="recoding.html#simp-int"><i class="fa fa-check"></i><b>4.6</b> Simplifying interval variables</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="recoding.html"><a href="recoding.html#cut-2"><i class="fa fa-check"></i><b>4.6.1</b> Simplifying interval variables using cut2()</a></li>
<li class="chapter" data-level="4.6.2" data-path="recoding.html"><a href="recoding.html#case-when"><i class="fa fa-check"></i><b>4.6.2</b> Simplifying interval variables with case_when</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="recoding.html"><a href="recoding.html#cross-tabs"><i class="fa fa-check"></i><b>4.7</b> Cross-tabulation tables</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="recoding.html"><a href="recoding.html#generating-cross-tabs"><i class="fa fa-check"></i><b>4.7.1</b> Generating cross-tabs</a></li>
<li class="chapter" data-level="4.7.2" data-path="recoding.html"><a href="recoding.html#adding-column-totals-to-cross-tabs"><i class="fa fa-check"></i><b>4.7.2</b> Adding column totals to cross-tabs</a></li>
<li class="chapter" data-level="4.7.3" data-path="recoding.html"><a href="recoding.html#column-percents"><i class="fa fa-check"></i><b>4.7.3</b> Adding column percents to cross-tabs</a></li>
<li class="chapter" data-level="4.7.4" data-path="recoding.html"><a href="recoding.html#export-crosstabs"><i class="fa fa-check"></i><b>4.7.4</b> Exporting cross-tabs for your word processor</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="recoding.html"><a href="recoding.html#mean-comparison-tables"><i class="fa fa-check"></i><b>4.8</b> Mean comparison tables</a></li>
<li class="chapter" data-level="4.9" data-path="recoding.html"><a href="recoding.html#review-of-this-chapters-commands-3"><i class="fa fa-check"></i><b>4.9</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html"><i class="fa fa-check"></i><b>5</b> Making controlled comparisons</a>
<ul>
<li class="chapter" data-level="5.1" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#getting-started-comparisons"><i class="fa fa-check"></i><b>5.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="5.2" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#stacked"><i class="fa fa-check"></i><b>5.2</b> Representing crosstabs with stacked bar graphs</a></li>
<li class="chapter" data-level="5.3" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#representing-mean-comparison-tables-with-boxplots"><i class="fa fa-check"></i><b>5.3</b> Representing mean comparison tables with boxplots</a></li>
<li class="chapter" data-level="5.4" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-crosstab"><i class="fa fa-check"></i><b>5.4</b> Adding a control to a crosstab</a></li>
<li class="chapter" data-level="5.5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-mean-comparison-table"><i class="fa fa-check"></i><b>5.5</b> Adding a control to a mean comparison table</a></li>
<li class="chapter" data-level="5.6" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#review-of-this-chapters-commands-4"><i class="fa fa-check"></i><b>5.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferences.html"><a href="inferences.html"><i class="fa fa-check"></i><b>6</b> Making inferences from sample means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferences.html"><a href="inferences.html#getting-started-inferences"><i class="fa fa-check"></i><b>6.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="6.2" data-path="inferences.html"><a href="inferences.html#constructing-a-confidence-interval-around-a-mean"><i class="fa fa-check"></i><b>6.2</b> Constructing a confidence interval around a mean</a></li>
<li class="chapter" data-level="6.3" data-path="inferences.html"><a href="inferences.html#ci-around-proportion"><i class="fa fa-check"></i><b>6.3</b> Constructing a confidence interval around a proportion</a></li>
<li class="chapter" data-level="6.4" data-path="inferences.html"><a href="inferences.html#ci-around-proportions"><i class="fa fa-check"></i><b>6.4</b> Constructing confidence intervals around several proportions at once</a></li>
<li class="chapter" data-level="6.5" data-path="inferences.html"><a href="inferences.html#t-test-ind-means"><i class="fa fa-check"></i><b>6.5</b> T-test of independent means</a></li>
<li class="chapter" data-level="6.6" data-path="inferences.html"><a href="inferences.html#caution-about-statistical-significance"><i class="fa fa-check"></i><b>6.6</b> Caution about “statistical significance”</a></li>
<li class="chapter" data-level="6.7" data-path="inferences.html"><a href="inferences.html#t-test-ind-props"><i class="fa fa-check"></i><b>6.7</b> T-test of independent proportions</a></li>
<li class="chapter" data-level="6.8" data-path="inferences.html"><a href="inferences.html#review-of-this-chapters-commands-5"><i class="fa fa-check"></i><b>6.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html"><i class="fa fa-check"></i><b>7</b> From chi-squared to somers’ d</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#getting-started-chi"><i class="fa fa-check"></i><b>7.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="7.2" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#chi-squared"><i class="fa fa-check"></i><b>7.2</b> Calculating chi-squared</a></li>
<li class="chapter" data-level="7.3" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#lambda"><i class="fa fa-check"></i><b>7.3</b> Lambda and the PREs</a></li>
<li class="chapter" data-level="7.4" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#cramers-v"><i class="fa fa-check"></i><b>7.4</b> Cramer’s V</a></li>
<li class="chapter" data-level="7.5" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#somers-d"><i class="fa fa-check"></i><b>7.5</b> Somers’ D</a></li>
<li class="chapter" data-level="7.6" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#review-of-this-chapters-commands-6"><i class="fa fa-check"></i><b>7.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="pearsons-r.html"><a href="pearsons-r.html"><i class="fa fa-check"></i><b>8</b> Pearson’s r and linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="pearsons-r.html"><a href="pearsons-r.html#getting-started-pearsons-r"><i class="fa fa-check"></i><b>8.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="8.2" data-path="pearsons-r.html"><a href="pearsons-r.html#pearsons-r-1"><i class="fa fa-check"></i><b>8.2</b> Pearson’s R</a></li>
<li class="chapter" data-level="8.3" data-path="pearsons-r.html"><a href="pearsons-r.html#scatterplot"><i class="fa fa-check"></i><b>8.3</b> The scatterplot</a></li>
<li class="chapter" data-level="8.4" data-path="pearsons-r.html"><a href="pearsons-r.html#bivariate-regression"><i class="fa fa-check"></i><b>8.4</b> Bivariate linear regression</a></li>
<li class="chapter" data-level="8.5" data-path="pearsons-r.html"><a href="pearsons-r.html#residuals"><i class="fa fa-check"></i><b>8.5</b> Residuals</a></li>
<li class="chapter" data-level="8.6" data-path="pearsons-r.html"><a href="pearsons-r.html#review-of-this-chapters-commands-7"><i class="fa fa-check"></i><b>8.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#getting-started-multiple-regression"><i class="fa fa-check"></i><b>9.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#multiple-regression"><i class="fa fa-check"></i><b>9.2</b> Multiple regression</a></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#residuals-in-multiple-regression"><i class="fa fa-check"></i><b>9.3</b> Residuals in multiple regression</a></li>
<li class="chapter" data-level="9.4" data-path="regression.html"><a href="regression.html#stargazer"><i class="fa fa-check"></i><b>9.4</b> Stargazer output</a></li>
<li class="chapter" data-level="9.5" data-path="regression.html"><a href="regression.html#dummy-variables-in-multiple-regression"><i class="fa fa-check"></i><b>9.5</b> Dummy variables in multiple regression</a></li>
<li class="chapter" data-level="9.6" data-path="regression.html"><a href="regression.html#ordinal-variables-in-regression-analysis"><i class="fa fa-check"></i><b>9.6</b> Ordinal variables in regression analysis</a></li>
<li class="chapter" data-level="9.7" data-path="regression.html"><a href="regression.html#graphing-multiple-regression"><i class="fa fa-check"></i><b>9.7</b> Graphing multiple regression</a></li>
<li class="chapter" data-level="9.8" data-path="regression.html"><a href="regression.html#review-of-this-chapters-commands-8"><i class="fa fa-check"></i><b>9.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="wild.html"><a href="wild.html"><i class="fa fa-check"></i><b>10</b> R in the wild</a>
<ul>
<li class="chapter" data-level="10.1" data-path="wild.html"><a href="wild.html#todays-lab-as-a-reference"><i class="fa fa-check"></i><b>10.1</b> Today’s lab as a reference</a></li>
<li class="chapter" data-level="10.2" data-path="wild.html"><a href="wild.html#importing-data-into-r"><i class="fa fa-check"></i><b>10.2</b> Importing data into R</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="wild.html"><a href="wild.html#importing-csv-files"><i class="fa fa-check"></i><b>10.2.1</b> Importing CSV files</a></li>
<li class="chapter" data-level="10.2.2" data-path="wild.html"><a href="wild.html#importing-excel-files"><i class="fa fa-check"></i><b>10.2.2</b> Importing Excel files</a></li>
<li class="chapter" data-level="10.2.3" data-path="wild.html"><a href="wild.html#importing-other-files"><i class="fa fa-check"></i><b>10.2.3</b> Importing other files</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="wild.html"><a href="wild.html#cleaning-data-in-r"><i class="fa fa-check"></i><b>10.3</b> Cleaning data in R</a></li>
<li class="chapter" data-level="10.4" data-path="wild.html"><a href="wild.html#resources"><i class="fa fa-check"></i><b>10.4</b> Online R resources</a></li>
<li class="chapter" data-level="10.5" data-path="wild.html"><a href="wild.html#the-last-command-how-to-get-help"><i class="fa fa-check"></i><b>10.5</b> The last command: how to get help</a></li>
<li class="chapter" data-level="10.6" data-path="wild.html"><a href="wild.html#the-strausz-method-for-improving-in-r"><i class="fa fa-check"></i><b>10.6</b> The Strausz method for improving in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="making-controlled-comparisons" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Making controlled comparisons<a href="making-controlled-comparisons.html#making-controlled-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="getting-started-comparisons" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Getting started with this chapter<a href="making-controlled-comparisons.html#getting-started-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To get started in today’s chapter, open the project that you made in lab 1. If you forgot how to do this, see the instructions in section <a href="tidyverse.html#exploring">2.2</a>.</p>
<p>Now, open a new script file and save it in your scripts folder as “chapter 5 practice.” Copy and paste this onto the page (updating the text so that it is about you):</p>
<pre><code>####################################
# Your name
# 20093 Chapter 5, Practice exercises
# Date started : Date last modified
####################################

#libraries------------------------------------------
library(tidyverse)
library(Hmisc)      #the cut2 command helps us simplify interval variables
library(scales)     #this is useful when the labels on our axes overlap
library(tigerstats) #colPerc can also be useful with crosstabs
library(flextable)  #this makes tables that we can easily export into a word processor</code></pre>
<p>Now select all the text on this page, run it, and save it.</p>
</div>
<div id="stacked" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Representing crosstabs with stacked bar graphs<a href="making-controlled-comparisons.html#stacked" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In chapter <a href="recoding.html#recoding">4</a> we learned how to generate crosstabs (and, crucially for interpretation, crosstabs with percents in columns). Crosstabs themselves have a lot of numbers on them, and can thus be difficult to interpret on their own. Many social scientists address this problem by generating graphs. A “stacked bar graph” is a really nice tool for visually depicting relationships in a bar graph. The code to generate stacked bar graphs is a little bit long and complex, so just feel free to copy and paste the below or the code from the “Strausz ggplot2 templates” which is in the “rscripts” folder that was in the zipped filed that you should have downloaded in section <a href="getting-started.html#add-files">1.3</a>. Let’s return to the relationship that we were looking at in section <a href="recoding.html#cross-tabs">4.7</a>, between education (our independent variable) and income (our dependent variable).</p>
<p>Here is the code to generate a stacked bar graph of this relationship:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="making-controlled-comparisons.html#cb105-1" tabindex="-1"></a><span class="co">#first, generate a dataframe called &quot;plotting.data&quot; based on grouped variables from #anes2024</span></span>
<span id="cb105-2"><a href="making-controlled-comparisons.html#cb105-2" tabindex="-1"></a>plotting.data<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span></span>
<span id="cb105-3"><a href="making-controlled-comparisons.html#cb105-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(education)<span class="sc">&amp;!</span><span class="fu">is.na</span>(income)) <span class="sc">%&gt;%</span> </span>
<span id="cb105-4"><a href="making-controlled-comparisons.html#cb105-4" tabindex="-1"></a>  <span class="fu">group_by</span>(education, income) <span class="sc">%&gt;%</span> </span>
<span id="cb105-5"><a href="making-controlled-comparisons.html#cb105-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb105-6"><a href="making-controlled-comparisons.html#cb105-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb105-7"><a href="making-controlled-comparisons.html#cb105-7" tabindex="-1"></a></span>
<span id="cb105-8"><a href="making-controlled-comparisons.html#cb105-8" tabindex="-1"></a><span class="co">#second, make the graph</span></span>
<span id="cb105-9"><a href="making-controlled-comparisons.html#cb105-9" tabindex="-1"></a><span class="fu">ggplot</span>(plotting.data, <span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> freq, <span class="at">fill=</span>income)) <span class="sc">+</span></span>
<span id="cb105-10"><a href="making-controlled-comparisons.html#cb105-10" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="sc">+</span></span>
<span id="cb105-11"><a href="making-controlled-comparisons.html#cb105-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>percent)<span class="sc">+</span></span>
<span id="cb105-12"><a href="making-controlled-comparisons.html#cb105-12" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>))<span class="sc">+</span> <span class="co">#this line is in here because without it the x-axis labels overlap. You can remove it if that isn’t a problem </span></span>
<span id="cb105-13"><a href="making-controlled-comparisons.html#cb105-13" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name=</span><span class="st">&quot;income&quot;</span>)<span class="sc">+</span> <span class="co">#this color palate is made to be readable for colorblind people</span></span>
<span id="cb105-14"><a href="making-controlled-comparisons.html#cb105-14" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Education and income in the 2024 ANES&quot;</span>)<span class="sc">+</span></span>
<span id="cb105-15"><a href="making-controlled-comparisons.html#cb105-15" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Education&quot;</span>)<span class="sc">+</span></span>
<span id="cb105-16"><a href="making-controlled-comparisons.html#cb105-16" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>One thing to note in this code: it begins by creating a new dataframe called “plotting.data.” When you run it, that dataframe will show up in your RStudio environment. If you run it again with new variables, the new “plotting data” that you make will overwrite the old one.</p>
<p>If it bothers you having that “plotting.data” object in your environment, you can always remove it with the command <code>rm(plotting.data)</code>.</p>
<p>Another thing to note: the “scale_fill_viridis_d()+” line of code asks R to use a color palette that is easy to read for people that are colorblind. There are many, many choices of color palette in R, and you are welcome to play around with colors, but it is also fine to just stick to this palette. If you’d rather have a black and white graph, there is code for that in the “Strausz ggplot2 templates” which is in the “rscripts” folder that was in the zipped filed that you should have downloaded in section <a href="getting-started.html#add-files">1.3</a>.</p>
<p>Looking at the graph, we can see that our X-axis is our independent variable, education, and our Y-axis is the column percentages of our dependent variable, income. Focusing on the yellow region, we can clearly see that each increase in education seems to correspond to an increase in the percent of people in the highest income earning category (with the possible exception of the movement between some college and associate degree). Focusing on the dark blue region, we can clearly see that, as level of education increases, the percent of people in the lowest income category decreases. In short, this graph has all of the same information that we got when looking at the crosstab that we generated with <code>colPerc(xtabs(~income+edu, data=anes2024))</code> from our previous lab, but it is much easier to take in a bunch of that information at the same time.</p>
</div>
<div id="representing-mean-comparison-tables-with-boxplots" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Representing mean comparison tables with boxplots<a href="making-controlled-comparisons.html#representing-mean-comparison-tables-with-boxplots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In addition to the histogram that we introduced in chapter 3, another useful way of representing the distribution of a single interval variable is with a boxplot. Here is the code for a boxplot of the variable (you can also find this code in the “Strausz ggplot2 templates” which is in the “rscripts” folder that was in the zipped filed that you should have downloaded in section <a href="getting-started.html#add-files">1.3</a>):</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="making-controlled-comparisons.html#cb106-1" tabindex="-1"></a><span class="co">#make a boxplot of govapproval</span></span>
<span id="cb106-2"><a href="making-controlled-comparisons.html#cb106-2" tabindex="-1"></a><span class="fu">ggplot</span>(states2025, <span class="fu">aes</span>(<span class="at">y =</span> govApproval2024)) <span class="sc">+</span></span>
<span id="cb106-3"><a href="making-controlled-comparisons.html#cb106-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;purple&quot;</span>, <span class="at">alpha=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb106-4"><a href="making-controlled-comparisons.html#cb106-4" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb106-5"><a href="making-controlled-comparisons.html#cb106-5" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Approval of governors in US states&quot;</span>)<span class="sc">+</span></span>
<span id="cb106-6"><a href="making-controlled-comparisons.html#cb106-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>)<span class="sc">+</span></span>
<span id="cb106-7"><a href="making-controlled-comparisons.html#cb106-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Proportion of state residents</span><span class="sc">\n</span><span class="st">approving of governor&quot;</span>)<span class="co">#the \n forces a second line in the axis title</span></span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>A boxplot gives us some interesting information about an interval variable. The bottom of the box is the 1st quartile (25% of cases have that value or lower) and the top of the box represents the 3rd quartile (75% of cases have that value or lower). The horizontal line represents the median value, and the vertical lines coming out of the box extend to the first quartile minus 1.5 multiplied by the interquartile range and the third quartile plus 1.5 multiplied by the interquartile range. If there were any outlier points above or below this line, they would be identified by individual points on the graph. The</p>
<p>Here is a labeled version of another boxplot for your reference:<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>
<img src="images/comparisons_1_boxplot.png" width="90%" /></p>
<p>So, in other words, we can learn a lot about a variable from a single graph!</p>
<p>Boxplots are also a useful way to look at the properties of an interval variable across several values of a nominal or ordinal variable, which is what we were doing with our mean comparison table in chapter <a href="recoding.html#recoding">4</a>. Let’s take a graphical look at the relationship between the region that a state is in and approval of the governor. We can set up that kind of graph with the following code:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="making-controlled-comparisons.html#cb107-1" tabindex="-1"></a><span class="co">#make boxplots of regions and govapproval</span></span>
<span id="cb107-2"><a href="making-controlled-comparisons.html#cb107-2" tabindex="-1"></a><span class="fu">ggplot</span>(states2025, <span class="fu">aes</span>(<span class="at">x =</span> region, <span class="at">y =</span> govApproval2024)) <span class="sc">+</span></span>
<span id="cb107-3"><a href="making-controlled-comparisons.html#cb107-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;purple&quot;</span>, <span class="at">alpha=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb107-4"><a href="making-controlled-comparisons.html#cb107-4" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Region and gubernatorial approval in US states&quot;</span>)<span class="sc">+</span></span>
<span id="cb107-5"><a href="making-controlled-comparisons.html#cb107-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Region&quot;</span>)<span class="sc">+</span></span>
<span id="cb107-6"><a href="making-controlled-comparisons.html#cb107-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Proportion of state residents that</span><span class="sc">\n</span><span class="st">approve of their governor, 2024&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>This graph shows us a lot of cool things. We can see that there is less variation among the states in the West than other regions, and that although the West has the lowest median approval the South appears to have the state with the lowest approval overall.</p>
</div>
<div id="adding-a-control-to-a-crosstab" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Adding a control to a crosstab<a href="making-controlled-comparisons.html#adding-a-control-to-a-crosstab" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far, we have learned to look at the relationship between pairs of variables. However, in real social scientific analysis we will often be interested in more than that. We will be interested in other factors that could be the true cause of variation in our dependent variable. If we look at the relationship between our independent and dependent variable at different values of a control variable and there no longer seems to be a relationship, then we can say that the correlation that we observe between our independent and dependent variable is <strong>spurious</strong>. If the relationship between the independent and dependent variable is roughly the same at different values of a control, we call the relationship between the independent and dependent variables, controlling for the third, <strong>additive</strong>. If the relationship between the independent and dependent variables is different at different values of a control, we call that relationship an <strong>interaction</strong>.</p>
<p>Let’s return to the relationship that we looked at earlier, between education and income. Here is the crosstab that we generated in chapter <a href="recoding.html#recoding">4</a>:</p>
<pre><code>##                       education
## income                 less than high school high school some college     ba graduate degree
##   under $9,999                         31.64       15.09         7.98   5.25            4.55
##   $10,000 to $29,999                   25.39       17.18        14.56   5.25            2.42
##   $30,000 to $59,999                   22.27       29.85        23.58  15.82            9.48
##   $60,000 to $99,999                   12.89       21.04        23.83  22.92           18.18
##   $100,000 to $249,999                  7.42       14.43        25.78  42.28           47.20
##   $250,000 or more                      0.39        2.42         4.27   8.49           18.18
##   Total                               100.00      100.00       100.00 100.00          100.00</code></pre>
<p>Let’s look at the row representing the people who make $250,000 or more per year. As we move from the lowest level of education to the highest, we can see that the percent of people in the highest income category moves from .39% to 18.18%. We can actually subtract .39 from 18.18 to say that the effect size is roughly 17.79%. In other words, 17.79% more people with the highest degree of education are in the highest income category than are people in the lowest education category.</p>
<p>Do we think that this result would be roughly the same for men and women? To answer this question, we can use a neat tool that we have actually played with a bit in previous chapters: the “filter” command that is a part of the dplyr package (and thus works with pipes). The ANES dataset has a variable called female, where 0 means “men” and 1 means “women.” Let’s have R make that crosstab again, but only for men, and then again, but only for women. To do that, we can use this code:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="making-controlled-comparisons.html#cb109-1" tabindex="-1"></a><span class="co">#men only</span></span>
<span id="cb109-2"><a href="making-controlled-comparisons.html#cb109-2" tabindex="-1"></a><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(female<span class="sc">==</span><span class="dv">0</span>)))</span></code></pre></div>
<pre><code>##                       education
## income                 less than high school high school some college     ba graduate degree
##   under $9,999                         27.05       12.31         6.29   4.19            4.09
##   $10,000 to $29,999                   18.03       16.14        10.16   4.35            1.23
##   $30,000 to $59,999                   28.69       30.79        22.03  14.35            9.41
##   $60,000 to $99,999                   16.39       22.08        25.89  20.81           14.93
##   $100,000 to $249,999                  9.02       16.77        30.76  46.94           48.88
##   $250,000 or more                      0.82        1.91         4.86   9.35           21.47
##   Total                               100.00      100.00       100.00 100.00          100.00</code></pre>
<p><strong>A quick note</strong>: if we wanted to use filter with a variable whose values are defined by text, such as our income variable, we must put the text in quotation marks. Here, we do not have to use quotation marks because female is defined numerically.</p>
<p>If we do the same comparison that we did above, we can see that as men more from the lowest to the highest education category, the percent in the highest income category increases from .82% to 21.47%. The total effect size is about 20.65%, which is a bit higher than the 17.79% overall effect size that we witnessed above.</p>
<p>To save this crosstab as in a word file that we can easily pull into various word processors, we can use this code, based on what we did in Section <a href="recoding.html#export-crosstabs">4.7.4</a>.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="making-controlled-comparisons.html#cb111-1" tabindex="-1"></a>ctab1men<span class="ot">&lt;-</span><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024 </span>
<span id="cb111-2"><a href="making-controlled-comparisons.html#cb111-2" tabindex="-1"></a>                              <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sex<span class="sc">==</span><span class="dv">0</span>)))</span>
<span id="cb111-3"><a href="making-controlled-comparisons.html#cb111-3" tabindex="-1"></a>ctab1men<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(ctab1men)<span class="sc">%&gt;%</span><span class="fu">rownames_to_column</span>(<span class="st">&quot;income&quot;</span>)</span>
<span id="cb111-4"><a href="making-controlled-comparisons.html#cb111-4" tabindex="-1"></a><span class="fu">flextable</span>(ctab1men) <span class="sc">%&gt;%</span> <span class="fu">save_as_docx</span>(<span class="at">path=</span><span class="st">&quot;ctab1men.docx&quot;</span>)</span></code></pre></div>
<p>Now let’s look at women only:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="making-controlled-comparisons.html#cb112-1" tabindex="-1"></a><span class="co">#women only</span></span>
<span id="cb112-2"><a href="making-controlled-comparisons.html#cb112-2" tabindex="-1"></a><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(female<span class="sc">==</span><span class="dv">1</span>)))</span></code></pre></div>
<pre><code>##                       education
## income                 less than high school high school some college     ba graduate degree
##   under $9,999                         35.34       17.89         9.25   6.23            4.97
##   $10,000 to $29,999                   32.33       18.35        17.85   5.93            3.50
##   $30,000 to $59,999                   16.54       28.90        24.76  17.21            9.39
##   $60,000 to $99,999                    9.77       19.95        22.32  24.78           21.18
##   $100,000 to $249,999                  6.02       11.93        22.00  38.13           45.86
##   $250,000 or more                      0.00        2.98         3.83   7.72           15.10
##   Total                               100.00      100.00       100.00 100.00          100.00</code></pre>
<p>Applying the same analysis that we did above, we can see that as women’s education level increases from the lowest to the highest level, the percent of people in the highest income bracket moves from 0% to 15.1%; a total effect size of 15.1% (compared with 20.65% for men). In other words, this data suggests that both men and women are economically rewarded for more education, but that men seem to be rewarded a bit more. If we were to write up these results, at this point we would have to use our own judgment to decide whether the effect size differs enough to call the relationship between education and income controlling for gender an interaction, or whether it makes more sense to call it additive. We can use more advanced statistical tools to make that determination with more rigor, but for now, we will rely on our judgment.</p>
<p>We can also save this table as a Word document, using the following code:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="making-controlled-comparisons.html#cb114-1" tabindex="-1"></a>ctab1women<span class="ot">&lt;-</span><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024 </span>
<span id="cb114-2"><a href="making-controlled-comparisons.html#cb114-2" tabindex="-1"></a>                              <span class="sc">%&gt;%</span> <span class="fu">filter</span>(female<span class="sc">==</span><span class="dv">1</span>)))</span>
<span id="cb114-3"><a href="making-controlled-comparisons.html#cb114-3" tabindex="-1"></a>ctab1women<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(ctab1women)<span class="sc">%&gt;%</span><span class="fu">rownames_to_column</span>(<span class="st">&quot;income&quot;</span>)</span>
<span id="cb114-4"><a href="making-controlled-comparisons.html#cb114-4" tabindex="-1"></a><span class="fu">flextable</span>(ctab1women) <span class="sc">%&gt;%</span> <span class="fu">save_as_docx</span>(<span class="at">path=</span><span class="st">&quot;ctab1women.docx&quot;</span>)</span></code></pre></div>
<p>There is not a single tool to graph relationships between three ordinal or nominal variables in an easy to interpret way. Instead, we can use the filter() command from above to make two graphs, and then use insert table in our word processor to nearly display them side by side.</p>
<p>Here is the code for the graph for only men (with the line <code>"filter(female==0) %&gt;% #filtering so that we only look at men</code>” added):</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="making-controlled-comparisons.html#cb115-1" tabindex="-1"></a>plotting.data<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span></span>
<span id="cb115-2"><a href="making-controlled-comparisons.html#cb115-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(income)<span class="sc">&amp;!</span><span class="fu">is.na</span>(education)) <span class="sc">%&gt;%</span> </span>
<span id="cb115-3"><a href="making-controlled-comparisons.html#cb115-3" tabindex="-1"></a>  <span class="fu">filter</span>(female<span class="sc">==</span><span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="co">#filtering so that we only look at men</span></span>
<span id="cb115-4"><a href="making-controlled-comparisons.html#cb115-4" tabindex="-1"></a>  <span class="fu">group_by</span>(education, income) <span class="sc">%&gt;%</span> </span>
<span id="cb115-5"><a href="making-controlled-comparisons.html#cb115-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb115-6"><a href="making-controlled-comparisons.html#cb115-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb115-7"><a href="making-controlled-comparisons.html#cb115-7" tabindex="-1"></a><span class="fu">ggplot</span>(plotting.data, <span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> freq, <span class="at">fill=</span>income)) <span class="sc">+</span></span>
<span id="cb115-8"><a href="making-controlled-comparisons.html#cb115-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="sc">+</span></span>
<span id="cb115-9"><a href="making-controlled-comparisons.html#cb115-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>percent)<span class="sc">+</span></span>
<span id="cb115-10"><a href="making-controlled-comparisons.html#cb115-10" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>))<span class="sc">+</span></span>
<span id="cb115-11"><a href="making-controlled-comparisons.html#cb115-11" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>()<span class="sc">+</span></span>
<span id="cb115-12"><a href="making-controlled-comparisons.html#cb115-12" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Education and income for men in the 2024 ANES&quot;</span>)<span class="sc">+</span></span>
<span id="cb115-13"><a href="making-controlled-comparisons.html#cb115-13" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Education&quot;</span>)<span class="sc">+</span></span>
<span id="cb115-14"><a href="making-controlled-comparisons.html#cb115-14" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>And here is the code for the graph for only women:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="making-controlled-comparisons.html#cb116-1" tabindex="-1"></a>plotting.data<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span></span>
<span id="cb116-2"><a href="making-controlled-comparisons.html#cb116-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(income)<span class="sc">&amp;!</span><span class="fu">is.na</span>(education)) <span class="sc">%&gt;%</span> </span>
<span id="cb116-3"><a href="making-controlled-comparisons.html#cb116-3" tabindex="-1"></a>  <span class="fu">filter</span>(female<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="co">#filtering so that we only look at women</span></span>
<span id="cb116-4"><a href="making-controlled-comparisons.html#cb116-4" tabindex="-1"></a>  <span class="fu">group_by</span>(education, income) <span class="sc">%&gt;%</span> </span>
<span id="cb116-5"><a href="making-controlled-comparisons.html#cb116-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb116-6"><a href="making-controlled-comparisons.html#cb116-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb116-7"><a href="making-controlled-comparisons.html#cb116-7" tabindex="-1"></a><span class="fu">ggplot</span>(plotting.data, <span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> freq, <span class="at">fill=</span>income)) <span class="sc">+</span></span>
<span id="cb116-8"><a href="making-controlled-comparisons.html#cb116-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="sc">+</span></span>
<span id="cb116-9"><a href="making-controlled-comparisons.html#cb116-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels=</span>percent)<span class="sc">+</span></span>
<span id="cb116-10"><a href="making-controlled-comparisons.html#cb116-10" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>))<span class="sc">+</span></span>
<span id="cb116-11"><a href="making-controlled-comparisons.html#cb116-11" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>()<span class="sc">+</span></span>
<span id="cb116-12"><a href="making-controlled-comparisons.html#cb116-12" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Education and income for women in the 2024 ANES&quot;</span>)<span class="sc">+</span></span>
<span id="cb116-13"><a href="making-controlled-comparisons.html#cb116-13" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Education&quot;</span>)<span class="sc">+</span></span>
<span id="cb116-14"><a href="making-controlled-comparisons.html#cb116-14" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
</div>
<div id="adding-a-control-to-a-mean-comparison-table" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Adding a control to a mean comparison table<a href="making-controlled-comparisons.html#adding-a-control-to-a-mean-comparison-table" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The ANES survey has a number of “feeling thermometer” questions, where respondents were asked how warmly or coldly they felt toward institutions, individuals, and groups of people. These questions all range from 0 (meaning that the respondent feel very negatively toward the subject), to 100 (meaning that the respondent feels very positively about the subject).</p>
<p>For this section, I am going to treat the feeling thermometer about the police as my dependent variable. For my independent variable, I am going to look at whether or not a person watches NCIS, a TV drama that, according to the <a href="https://www.imdb.com/title/tt0364845/">Internet Movie Database</a>, “Follows the Major Case Response Team (MCRT) from the Naval Criminal Investigative Service (NCIS), as they get to the bottom of criminal cases connected to Navy and Marine Corps personnel.” Do people that watch that show, which portrays the police as its protagonists, like the police more than people that don’t watch that show?</p>
<p>The ncis variable is currently coded as as a dummy variable, with those who don’t watch the show getting a 0 and those who watch the show getting a 1. To make our output easier to read, I am going to generate a new version of that variable with the values “watches NCIS” and “doesn’t watch”, using the same technique that I used in section <a href="recoding.html#recode-dummy">4.5</a>. Note that I call the new variable ncis2, so that I preserve the original ncis variable instead of writing over it:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="making-controlled-comparisons.html#cb117-1" tabindex="-1"></a>anes2024<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb117-2"><a href="making-controlled-comparisons.html#cb117-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ncis2=</span><span class="fu">recode</span>(ncis, <span class="st">&#39;1&#39;</span><span class="ot">=</span><span class="st">&quot;watches NCIS&quot;</span>,<span class="st">&#39;0&#39;</span><span class="ot">=</span><span class="st">&quot;doesn&#39;t watch&quot;</span>))</span></code></pre></div>
<p>If you run<code>table(anes2024$ncis2)</code>, you will see 4,753 people in our sample don’t regularly watch NCIS, and 523 do regularly watch NCIS.</p>
<p>Now, let’s make a mean comparison table to see how the mean police feeling thermometer score differs between NCIS watcher and non-watchers:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="making-controlled-comparisons.html#cb118-1" tabindex="-1"></a>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb118-2"><a href="making-controlled-comparisons.html#cb118-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ft_police)<span class="sc">&amp;!</span><span class="fu">is.na</span>(ncis2)) <span class="sc">%&gt;%</span> </span>
<span id="cb118-3"><a href="making-controlled-comparisons.html#cb118-3" tabindex="-1"></a>  <span class="fu">group_by</span>(ncis2) <span class="sc">%&gt;%</span> </span>
<span id="cb118-4"><a href="making-controlled-comparisons.html#cb118-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(ft_police), <span class="at">sd=</span><span class="fu">sd</span>(ft_police), <span class="at">n=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   ncis2          mean    sd     n
##   &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 doesn&#39;t watch  69.0  24.5  4226
## 2 watches NCIS   76.1  21.1   474</code></pre>
<p>This tells us that people that watch NCIS give the police a mean score of 76.1 on average, and people that don’t watch the show give the police a mean score of 69. The standard deviations are both pretty large, which suggests that there is a lot of variation in feelings about the police among both NCIS watchers and non-watchers.</p>
<p>To graph this relationship, we can use this code:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="making-controlled-comparisons.html#cb120-1" tabindex="-1"></a><span class="fu">ggplot</span>(anes2024 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ncis2)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ft_police)), </span>
<span id="cb120-2"><a href="making-controlled-comparisons.html#cb120-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> ncis2, <span class="at">y =</span> ft_police)) <span class="sc">+</span></span>
<span id="cb120-3"><a href="making-controlled-comparisons.html#cb120-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;purple&quot;</span>, <span class="at">alpha=</span><span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb120-4"><a href="making-controlled-comparisons.html#cb120-4" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;ANES 2024, Feelings about police by NCIS viewership&quot;</span>)<span class="sc">+</span></span>
<span id="cb120-5"><a href="making-controlled-comparisons.html#cb120-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>)<span class="sc">+</span> <span class="co">#I use null here because the value labels for my NCIS variable explain what is going on to readers, so an additional axis label is not necessary</span></span>
<span id="cb120-6"><a href="making-controlled-comparisons.html#cb120-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Feelings about police</span><span class="sc">\n</span><span class="st">(100 is warm and 0 is cold)&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>This graph shows us that the feeling thermometer scores for the police seem to have ranged from 0 to 100 for both NCIS viewers and non-viewers. However, the median score for non-NCIS watchers appears to be right around the first quartile for NCIS watchers. This graph does suggest that, overall, NCIS watchers seem to like the police more than non-watchers.</p>
<p>When doing this analysis, I wondered whether what is really going might have to do with ideology. Maybe conservatives are more likely to both watch NCIS and like the police than are liberals. To test this hypothesis, I took a look at the ideology3 variable that I generated in section <a href="recoding.html#recode-nom">4.2</a>.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<p>Now let’s add our control variable to our mean comparison table. It is easier to add a control variable into a mean comparison table than it was to add a control variable into our cross tab. To do so, we can use the following code:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="making-controlled-comparisons.html#cb121-1" tabindex="-1"></a>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb121-2"><a href="making-controlled-comparisons.html#cb121-2" tabindex="-1"></a>  <span class="co">#first I filter out the NAs for all 3 variables</span></span>
<span id="cb121-3"><a href="making-controlled-comparisons.html#cb121-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ft_police)<span class="sc">&amp;!</span><span class="fu">is.na</span>(ideology3)<span class="sc">&amp;!</span><span class="fu">is.na</span>(ncis2)) <span class="sc">%&gt;%</span></span>
<span id="cb121-4"><a href="making-controlled-comparisons.html#cb121-4" tabindex="-1"></a>  <span class="co">#then I group by the control first, and then the IV</span></span>
<span id="cb121-5"><a href="making-controlled-comparisons.html#cb121-5" tabindex="-1"></a>  <span class="fu">group_by</span>(ideology3, ncis2) <span class="sc">%&gt;%</span> </span>
<span id="cb121-6"><a href="making-controlled-comparisons.html#cb121-6" tabindex="-1"></a>  <span class="co">#then I summarise in the same way that I do with a two-variable table</span></span>
<span id="cb121-7"><a href="making-controlled-comparisons.html#cb121-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(ft_police), <span class="at">sd=</span><span class="fu">sd</span>(ft_police), <span class="at">n=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
## # Groups:   ideology3 [3]
##   ideology3    ncis2          mean    sd     n
##   &lt;ord&gt;        &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 liberal      doesn&#39;t watch  58.4  25.3  1334
## 2 liberal      watches NCIS   67.9  23.1   103
## 3 moderate     doesn&#39;t watch  67.8  22.8   906
## 4 moderate     watches NCIS   74.8  20.4   104
## 5 conservative doesn&#39;t watch  79.9  18.9  1472
## 6 conservative watches NCIS   83.3  17.1   181</code></pre>
<p>The comments explain what is happening in the code. It is almost the same as the code for a two variable mean comparison table, but I group by the control (first) and then the independent variable, rather than just grouping by the independent variable, as I did in the two-variable code.</p>
<p>Let’s look at this output. First, focus on the first two rows. They tell us that liberals who watch NCIS feel 9.5 points more warmly than liberals that don’t watch NCIS (because 67.9-58.4=9.5). But among moderates, the effect size is smaller (7), and among conservatives, the effect size is even smaller still (3.4). Thus, we can say that the relationship between NCIS watching and feelings about the police is different for respondents with different ideological backgrounds. We thus call this an <strong>interactive relationship</strong>.</p>
<p>We can also notice that liberals who watch NCIS feel almost exactly the same about the police than do moderates who do <strong>not</strong> watch the show, and moderates who watch NCIS feel 5.1 points more coldly toward the police than do conservatives who do <strong>not</strong> watch the show. In other words, ideology also appears to be related to feeling about the police.</p>
<p>We can save this three variable mean comparison table like this:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="making-controlled-comparisons.html#cb123-1" tabindex="-1"></a>mc2<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb123-2"><a href="making-controlled-comparisons.html#cb123-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ft_police)<span class="sc">&amp;!</span><span class="fu">is.na</span>(ideology3)<span class="sc">&amp;!</span><span class="fu">is.na</span>(ncis2)) <span class="sc">%&gt;%</span></span>
<span id="cb123-3"><a href="making-controlled-comparisons.html#cb123-3" tabindex="-1"></a>  <span class="fu">group_by</span>(ideology3, ncis2) <span class="sc">%&gt;%</span> </span>
<span id="cb123-4"><a href="making-controlled-comparisons.html#cb123-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(ft_police), <span class="at">sd=</span><span class="fu">sd</span>(ft_police), <span class="at">n=</span><span class="fu">n</span>())</span>
<span id="cb123-5"><a href="making-controlled-comparisons.html#cb123-5" tabindex="-1"></a><span class="fu">flextable</span>(mc2)<span class="sc">%&gt;%</span> </span>
<span id="cb123-6"><a href="making-controlled-comparisons.html#cb123-6" tabindex="-1"></a>  <span class="fu">save_as_docx</span>(<span class="at">path=</span><span class="st">&quot;mc2.docx&quot;</span>)</span></code></pre></div>
<p>To graphically represent this relationship, we can use this code (which you can also find in the “Strausz ggplot2 templates” which is in the “rscripts” folder that was in the zipped filed that you should have downloaded in section <a href="getting-started.html#add-files">1.3</a>):</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="making-controlled-comparisons.html#cb124-1" tabindex="-1"></a><span class="fu">ggplot</span>(anes2024 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ideology3) <span class="sc">&amp;</span> (<span class="sc">!</span><span class="fu">is.na</span>(ncis2))), </span>
<span id="cb124-2"><a href="making-controlled-comparisons.html#cb124-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> ideology3, <span class="at">y =</span> ft_police, <span class="at">fill=</span>ncis2)) <span class="sc">+</span></span>
<span id="cb124-3"><a href="making-controlled-comparisons.html#cb124-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb124-4"><a href="making-controlled-comparisons.html#cb124-4" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;ANES 2024, Feelings about police by ideology</span><span class="sc">\n</span><span class="st">and NCIS viewership&quot;</span>)<span class="sc">+</span></span>
<span id="cb124-5"><a href="making-controlled-comparisons.html#cb124-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>)<span class="sc">+</span></span>
<span id="cb124-6"><a href="making-controlled-comparisons.html#cb124-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Feelings about the police</span><span class="sc">\n</span><span class="st">(100 is warm and 0 is cold)&quot;</span>)<span class="sc">+</span></span>
<span id="cb124-7"><a href="making-controlled-comparisons.html#cb124-7" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">&quot;NCIS&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>This boxplot clearly shows how the relationship between NCIS viewership and feelings about the police is stronger for liberals than it was for conservatives. This is a really nice example of an interaction, and it suggests that NCIS viewership may have had different meanings for liberals, moderates, and conservatives.</p>
</div>
<div id="review-of-this-chapters-commands-4" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Review of this chapter’s commands<a href="making-controlled-comparisons.html#review-of-this-chapters-commands-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table>
<colgroup>
<col width="11%" />
<col width="81%" />
<col width="7%" />
</colgroup>
<thead>
<tr>
<th align="left">Command</th>
<th align="left">Purpose</th>
<th align="left">Library</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">filter(VARIABLE==VALUE) %&gt;%</td>
<td align="left">A way to filter out cases that you are not interested in. If the value you are interested in is coded as text (as is the case with our nominal and ordinal variables), be sure to put it in quotation marks.</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="4">
<li id="fn4"><p>This graph is generated with the states2010 dataframe that I used in previous versions of the workbook. The states2025 dataframe that we are using for this workbook also as a “percent evangelical” variable, but is data from 2020, while the data in this graph is from 2010. This graph also uses a different measure of percent evangelical from the 2010 data.<a href="making-controlled-comparisons.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>If you did not run the code to generate that variable at the time, you should generate the variable ideology3 using the code in section <a href="recoding.html#recode-nom">4.2</a> before continuing with thise section.<a href="making-controlled-comparisons.html#fnref5" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="recoding.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inferences.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/05-comparisons.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
