<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Recoding and comparing values of variables | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</title>
  <meta name="description" content="This is the preface of the workbook" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Recoding and comparing values of variables | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the preface of the workbook" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Recoding and comparing values of variables | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  
  <meta name="twitter:description" content="This is the preface of the workbook" />
  

<meta name="author" content="Michael Strausz" />


<meta name="date" content="2025-09-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="graphing.html"/>
<link rel="next" href="making-controlled-comparisons.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Are You Ready for R?</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="whats-new-in-version-3.html"><a href="whats-new-in-version-3.html"><i class="fa fa-check"></i>What’s new in version 3.0?</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#why-r"><i class="fa fa-check"></i><b>1.1</b> Why R?</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#class-project"><i class="fa fa-check"></i><b>1.2</b> Create a project for this class</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#add-files"><i class="fa fa-check"></i><b>1.3</b> Add the course files to your project</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#using-the-console"><i class="fa fa-check"></i><b>1.4</b> Using the Console</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="getting-started.html"><a href="getting-started.html#rules-about-naming-objects"><i class="fa fa-check"></i><b>1.4.1</b> Rules about naming objects</a></li>
<li class="chapter" data-level="1.4.2" data-path="getting-started.html"><a href="getting-started.html#common-practices-when-naming-objects"><i class="fa fa-check"></i><b>1.4.2</b> Common practices when naming objects</a></li>
<li class="chapter" data-level="1.4.3" data-path="getting-started.html"><a href="getting-started.html#about-vectors"><i class="fa fa-check"></i><b>1.4.3</b> About vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#first-script"><i class="fa fa-check"></i><b>1.5</b> Writing your first R script</a></li>
<li class="chapter" data-level="1.6" data-path="getting-started.html"><a href="getting-started.html#wont-load"><i class="fa fa-check"></i><b>1.6</b> What do to if the “load” command doesn’t load the dataframe</a></li>
<li class="chapter" data-level="1.7" data-path="getting-started.html"><a href="getting-started.html#review-of-this-chapters-commands"><i class="fa fa-check"></i><b>1.7</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>2</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tidyverse.html"><a href="tidyverse.html#install-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Installing packages</a></li>
<li class="chapter" data-level="2.2" data-path="tidyverse.html"><a href="tidyverse.html#exploring"><i class="fa fa-check"></i><b>2.2</b> Exploring dataframes</a></li>
<li class="chapter" data-level="2.3" data-path="tidyverse.html"><a href="tidyverse.html#org-script"><i class="fa fa-check"></i><b>2.3</b> Organizing your scripts</a></li>
<li class="chapter" data-level="2.4" data-path="tidyverse.html"><a href="tidyverse.html#welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>2.4</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="tidyverse.html"><a href="tidyverse.html#introducing-the-pipe-in-tidyverse"><i class="fa fa-check"></i><b>2.4.1</b> Introducing the ‘pipe’ in tidyverse</a></li>
<li class="chapter" data-level="2.4.2" data-path="tidyverse.html"><a href="tidyverse.html#select-in-tidyverse"><i class="fa fa-check"></i><b>2.4.2</b> select() in tidyverse</a></li>
<li class="chapter" data-level="2.4.3" data-path="tidyverse.html"><a href="tidyverse.html#a-warning-about-the-select-command"><i class="fa fa-check"></i><b>2.4.3</b> A warning about the select() command</a></li>
<li class="chapter" data-level="2.4.4" data-path="tidyverse.html"><a href="tidyverse.html#arrange-in-tidyverse"><i class="fa fa-check"></i><b>2.4.4</b> arrange() in tidyverse</a></li>
<li class="chapter" data-level="2.4.5" data-path="tidyverse.html"><a href="tidyverse.html#glimpse-in-tidyverse"><i class="fa fa-check"></i><b>2.4.5</b> glimpse() in tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tidyverse.html"><a href="tidyverse.html#review-of-this-chapters-commands-1"><i class="fa fa-check"></i><b>2.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>3</b> Graphing and describing variables</a>
<ul>
<li class="chapter" data-level="3.1" data-path="graphing.html"><a href="graphing.html#getting-started-tidyverse"><i class="fa fa-check"></i><b>3.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="graphing.html"><a href="graphing.html#start-graphing"><i class="fa fa-check"></i><b>3.2</b> Getting started with ggplot and graphing</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="graphing.html"><a href="graphing.html#bar-graph-nominal"><i class="fa fa-check"></i><b>3.2.1</b> Bar graphing a nominal variable</a></li>
<li class="chapter" data-level="3.2.2" data-path="graphing.html"><a href="graphing.html#remove-na"><i class="fa fa-check"></i><b>3.2.2</b> Removing the NA bar</a></li>
<li class="chapter" data-level="3.2.3" data-path="graphing.html"><a href="graphing.html#add-return"><i class="fa fa-check"></i><b>3.2.3</b> Adding a second line to a graph’s title</a></li>
<li class="chapter" data-level="3.2.4" data-path="graphing.html"><a href="graphing.html#saving-a-graph"><i class="fa fa-check"></i><b>3.2.4</b> Saving a graph</a></li>
<li class="chapter" data-level="3.2.5" data-path="graphing.html"><a href="graphing.html#bar-graph-ordinal"><i class="fa fa-check"></i><b>3.2.5</b> Bar graphing an ordinal variable</a></li>
<li class="chapter" data-level="3.2.6" data-path="graphing.html"><a href="graphing.html#what-to-do-about-overlapping-labels"><i class="fa fa-check"></i><b>3.2.6</b> What to do about overlapping labels</a></li>
<li class="chapter" data-level="3.2.7" data-path="graphing.html"><a href="graphing.html#histogram"><i class="fa fa-check"></i><b>3.2.7</b> Generating a histogram</a></li>
<li class="chapter" data-level="3.2.8" data-path="graphing.html"><a href="graphing.html#removing-scientific-notation-from-axes"><i class="fa fa-check"></i><b>3.2.8</b> Removing scientific notation from axes</a></li>
<li class="chapter" data-level="3.2.9" data-path="graphing.html"><a href="graphing.html#adjusting-bin-width-on-a-histogram"><i class="fa fa-check"></i><b>3.2.9</b> Adjusting bin width on a histogram</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion"><i class="fa fa-check"></i><b>3.3</b> Central tendancy and dispersion</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-nominal-variables"><i class="fa fa-check"></i><b>3.3.1</b> Central tendency and dispersion of nominal variables</a></li>
<li class="chapter" data-level="3.3.2" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-ordinal-variables"><i class="fa fa-check"></i><b>3.3.2</b> Central tendency and dispersion of ordinal variables</a></li>
<li class="chapter" data-level="3.3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion-of-interval-variables"><i class="fa fa-check"></i><b>3.3.3</b> Central tendancy and dispersion of interval variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="graphing.html"><a href="graphing.html#states-world"><i class="fa fa-check"></i><b>3.4</b> A note on using the states2025 and world2025</a></li>
<li class="chapter" data-level="3.5" data-path="graphing.html"><a href="graphing.html#review-of-this-chapters-commands-2"><i class="fa fa-check"></i><b>3.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="recoding.html"><a href="recoding.html"><i class="fa fa-check"></i><b>4</b> Recoding and comparing values of variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="recoding.html"><a href="recoding.html#getting-started-recoding"><i class="fa fa-check"></i><b>4.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="recoding.html"><a href="recoding.html#recode-nom"><i class="fa fa-check"></i><b>4.2</b> Recoding ordinal and nominal variables</a></li>
<li class="chapter" data-level="4.3" data-path="recoding.html"><a href="recoding.html#reverse-ord"><i class="fa fa-check"></i><b>4.3</b> Reversing the order of ordinal variables</a></li>
<li class="chapter" data-level="4.4" data-path="recoding.html"><a href="recoding.html#factor-as-numeric"><i class="fa fa-check"></i><b>4.4</b> Making ordinal variables numeric</a></li>
<li class="chapter" data-level="4.5" data-path="recoding.html"><a href="recoding.html#recode-dummy"><i class="fa fa-check"></i><b>4.5</b> Dealing with variables coded 0/1</a></li>
<li class="chapter" data-level="4.6" data-path="recoding.html"><a href="recoding.html#simp-int"><i class="fa fa-check"></i><b>4.6</b> Simplifying interval variables</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="recoding.html"><a href="recoding.html#cut-2"><i class="fa fa-check"></i><b>4.6.1</b> Simplifying interval variables using cut2()</a></li>
<li class="chapter" data-level="4.6.2" data-path="recoding.html"><a href="recoding.html#case-when"><i class="fa fa-check"></i><b>4.6.2</b> Simplifying interval variables with case_when</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="recoding.html"><a href="recoding.html#cross-tabs"><i class="fa fa-check"></i><b>4.7</b> Cross-tabulation tables</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="recoding.html"><a href="recoding.html#generating-cross-tabs"><i class="fa fa-check"></i><b>4.7.1</b> Generating cross-tabs</a></li>
<li class="chapter" data-level="4.7.2" data-path="recoding.html"><a href="recoding.html#adding-column-totals-to-cross-tabs"><i class="fa fa-check"></i><b>4.7.2</b> Adding column totals to cross-tabs</a></li>
<li class="chapter" data-level="4.7.3" data-path="recoding.html"><a href="recoding.html#column-percents"><i class="fa fa-check"></i><b>4.7.3</b> Adding column percents to cross-tabs</a></li>
<li class="chapter" data-level="4.7.4" data-path="recoding.html"><a href="recoding.html#export-crosstabs"><i class="fa fa-check"></i><b>4.7.4</b> Exporting cross-tabs for your word processor</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="recoding.html"><a href="recoding.html#mean-comparison-tables"><i class="fa fa-check"></i><b>4.8</b> Mean comparison tables</a></li>
<li class="chapter" data-level="4.9" data-path="recoding.html"><a href="recoding.html#review-of-this-chapters-commands-3"><i class="fa fa-check"></i><b>4.9</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html"><i class="fa fa-check"></i><b>5</b> Making controlled comparisons</a>
<ul>
<li class="chapter" data-level="5.1" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#getting-started-comparisons"><i class="fa fa-check"></i><b>5.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="5.2" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#stacked"><i class="fa fa-check"></i><b>5.2</b> Representing crosstabs with stacked bar graphs</a></li>
<li class="chapter" data-level="5.3" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#representing-mean-comparison-tables-with-boxplots"><i class="fa fa-check"></i><b>5.3</b> Representing mean comparison tables with boxplots</a></li>
<li class="chapter" data-level="5.4" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-crosstab"><i class="fa fa-check"></i><b>5.4</b> Adding a control to a crosstab</a></li>
<li class="chapter" data-level="5.5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-mean-comparison-table"><i class="fa fa-check"></i><b>5.5</b> Adding a control to a mean comparison table</a></li>
<li class="chapter" data-level="5.6" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#review-of-this-chapters-commands-4"><i class="fa fa-check"></i><b>5.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferences.html"><a href="inferences.html"><i class="fa fa-check"></i><b>6</b> Making inferences from sample means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferences.html"><a href="inferences.html#getting-started-inferences"><i class="fa fa-check"></i><b>6.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="6.2" data-path="inferences.html"><a href="inferences.html#constructing-a-confidence-interval-around-a-mean"><i class="fa fa-check"></i><b>6.2</b> Constructing a confidence interval around a mean</a></li>
<li class="chapter" data-level="6.3" data-path="inferences.html"><a href="inferences.html#ci-around-proportion"><i class="fa fa-check"></i><b>6.3</b> Constructing a confidence interval around a proportion</a></li>
<li class="chapter" data-level="6.4" data-path="inferences.html"><a href="inferences.html#ci-around-proportions"><i class="fa fa-check"></i><b>6.4</b> Constructing confidence intervals around several proportions at once</a></li>
<li class="chapter" data-level="6.5" data-path="inferences.html"><a href="inferences.html#t-test-ind-means"><i class="fa fa-check"></i><b>6.5</b> T-test of independent means</a></li>
<li class="chapter" data-level="6.6" data-path="inferences.html"><a href="inferences.html#caution-about-statistical-significance"><i class="fa fa-check"></i><b>6.6</b> Caution about “statistical significance”</a></li>
<li class="chapter" data-level="6.7" data-path="inferences.html"><a href="inferences.html#t-test-ind-props"><i class="fa fa-check"></i><b>6.7</b> T-test of independent proportions</a></li>
<li class="chapter" data-level="6.8" data-path="inferences.html"><a href="inferences.html#review-of-this-chapters-commands-5"><i class="fa fa-check"></i><b>6.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html"><i class="fa fa-check"></i><b>7</b> From chi-squared to somers’ d</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#getting-started-chi"><i class="fa fa-check"></i><b>7.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="7.2" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#chi-squared"><i class="fa fa-check"></i><b>7.2</b> Calculating chi-squared</a></li>
<li class="chapter" data-level="7.3" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#lambda"><i class="fa fa-check"></i><b>7.3</b> Lambda and the PREs</a></li>
<li class="chapter" data-level="7.4" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#cramers-v"><i class="fa fa-check"></i><b>7.4</b> Cramer’s V</a></li>
<li class="chapter" data-level="7.5" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#somers-d"><i class="fa fa-check"></i><b>7.5</b> Somers’ D</a></li>
<li class="chapter" data-level="7.6" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#review-of-this-chapters-commands-6"><i class="fa fa-check"></i><b>7.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="pearsons-r.html"><a href="pearsons-r.html"><i class="fa fa-check"></i><b>8</b> Pearson’s r and linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="pearsons-r.html"><a href="pearsons-r.html#getting-started-pearsons-r"><i class="fa fa-check"></i><b>8.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="8.2" data-path="pearsons-r.html"><a href="pearsons-r.html#pearsons-r-1"><i class="fa fa-check"></i><b>8.2</b> Pearson’s R</a></li>
<li class="chapter" data-level="8.3" data-path="pearsons-r.html"><a href="pearsons-r.html#scatterplot"><i class="fa fa-check"></i><b>8.3</b> The scatterplot</a></li>
<li class="chapter" data-level="8.4" data-path="pearsons-r.html"><a href="pearsons-r.html#bivariate-regression"><i class="fa fa-check"></i><b>8.4</b> Bivariate linear regression</a></li>
<li class="chapter" data-level="8.5" data-path="pearsons-r.html"><a href="pearsons-r.html#residuals"><i class="fa fa-check"></i><b>8.5</b> Residuals</a></li>
<li class="chapter" data-level="8.6" data-path="pearsons-r.html"><a href="pearsons-r.html#review-of-this-chapters-commands-7"><i class="fa fa-check"></i><b>8.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#getting-started-multiple-regression"><i class="fa fa-check"></i><b>9.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#multiple-regression"><i class="fa fa-check"></i><b>9.2</b> Multiple regression</a></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#residuals-in-multiple-regression"><i class="fa fa-check"></i><b>9.3</b> Residuals in multiple regression</a></li>
<li class="chapter" data-level="9.4" data-path="regression.html"><a href="regression.html#stargazer"><i class="fa fa-check"></i><b>9.4</b> Stargazer output</a></li>
<li class="chapter" data-level="9.5" data-path="regression.html"><a href="regression.html#dummy-variables-in-multiple-regression"><i class="fa fa-check"></i><b>9.5</b> Dummy variables in multiple regression</a></li>
<li class="chapter" data-level="9.6" data-path="regression.html"><a href="regression.html#ordinal-variables-in-regression-analysis"><i class="fa fa-check"></i><b>9.6</b> Ordinal variables in regression analysis</a></li>
<li class="chapter" data-level="9.7" data-path="regression.html"><a href="regression.html#graphing-multiple-regression"><i class="fa fa-check"></i><b>9.7</b> Graphing multiple regression</a></li>
<li class="chapter" data-level="9.8" data-path="regression.html"><a href="regression.html#review-of-this-chapters-commands-8"><i class="fa fa-check"></i><b>9.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="wild.html"><a href="wild.html"><i class="fa fa-check"></i><b>10</b> R in the wild</a>
<ul>
<li class="chapter" data-level="10.1" data-path="wild.html"><a href="wild.html#todays-lab-as-a-reference"><i class="fa fa-check"></i><b>10.1</b> Today’s lab as a reference</a></li>
<li class="chapter" data-level="10.2" data-path="wild.html"><a href="wild.html#importing-data-into-r"><i class="fa fa-check"></i><b>10.2</b> Importing data into R</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="wild.html"><a href="wild.html#importing-csv-files"><i class="fa fa-check"></i><b>10.2.1</b> Importing CSV files</a></li>
<li class="chapter" data-level="10.2.2" data-path="wild.html"><a href="wild.html#importing-excel-files"><i class="fa fa-check"></i><b>10.2.2</b> Importing Excel files</a></li>
<li class="chapter" data-level="10.2.3" data-path="wild.html"><a href="wild.html#importing-other-files"><i class="fa fa-check"></i><b>10.2.3</b> Importing other files</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="wild.html"><a href="wild.html#cleaning-data-in-r"><i class="fa fa-check"></i><b>10.3</b> Cleaning data in R</a></li>
<li class="chapter" data-level="10.4" data-path="wild.html"><a href="wild.html#resources"><i class="fa fa-check"></i><b>10.4</b> Online R resources</a></li>
<li class="chapter" data-level="10.5" data-path="wild.html"><a href="wild.html#the-last-command-how-to-get-help"><i class="fa fa-check"></i><b>10.5</b> The last command: how to get help</a></li>
<li class="chapter" data-level="10.6" data-path="wild.html"><a href="wild.html#the-strausz-method-for-improving-in-r"><i class="fa fa-check"></i><b>10.6</b> The Strausz method for improving in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="recoding" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Recoding and comparing values of variables<a href="recoding.html#recoding" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="getting-started-recoding" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Getting started with this chapter<a href="recoding.html#getting-started-recoding" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To get started in today’s chapter, open the project that you made in lab 1. If you forgot how to do this, see the instructions in section <a href="tidyverse.html#exploring">2.2</a>.</p>
<p>We are going to install three new packages to use today.They are called “epiDisplay”, “Hmisc”, and “flextable.” Enter these three commands into your Console one by one:</p>
<pre><code>install.packages(&quot;Hmisc&quot;)
install.packages(&quot;tigerstats&quot;)
install.packages(&quot;flextable&quot;)</code></pre>
<p>Now, open a new script file and save it in your scripts folder as “chapter 4 practice.” Copy and paste this onto the page (updating the text so that it is about you):</p>
<pre><code>####################################
# Your name
# 20093 Chapter 4, Practice exercises
# Date started : Date last modified
####################################

#libraries------------------------------------------
library(tidyverse)
library(epiDisplay)   #the tab1 command helps us make nice frequency tables
library(Hmisc)        #the cut2 command helps us simplify interval variables
library(tigerstats)   #colPerc can also be useful with crosstabs
library(flextable)    #this makes tables that we can easily export into a word processor</code></pre>
<p>Now select all the text on this page, run it, and save it.</p>
</div>
<div id="recode-nom" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Recoding ordinal and nominal variables<a href="recoding.html#recode-nom" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are times that you will want to change the values of variables. Perhaps you are interested in one particular value of a key variable (such as married people, or high-income countries). Perhaps your variable has some values which you would like to treat as missing. Or, perhaps you will want to simplify a variable, or change a variable from character to numeric or vice versa. When doing so, you will have two powerful allies: the mutate() command and the recode() command, both available through the dplyr package that comes with tidyverse.</p>
<p>To start, let’s take a look at the ideology variable in the anes2024 dataset. We can use the tab1() command that we learned last lesson to look at how the values are distributed, running this command</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="recoding.html#cb65-1" tabindex="-1"></a><span class="fu">tab1</span>(anes2024<span class="sc">$</span>ideology)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre><code>## anes2024$ideology : 
##                       Frequency   %(NA+)   %(NA-)
## very liberal                250      4.5      5.3
## liberal                     819     14.8     17.3
## slightly liberal            543      9.8     11.5
## moderate                   1187     21.5     25.1
## slightly conservative       594     10.8     12.6
## conservative               1030     18.7     21.8
## very conservative           309      5.6      6.5
## NA&#39;s                        789     14.3      0.0
##   Total                    5521    100.0    100.0</code></pre>
<p>Looking at this output, we can see that there are seven possible values (excluding the NAs), ranging from “very liberal” to “very conservative.” There are times when we might want all of this detail, and we should not throw away data. However, we will often just want to compare liberals, moderates, and conservatives. To simplify this variable, we will first tell R to make a new version of the ANES dataframe that will house our new variable. Then, we will use mutate and recode to give values for our new variable. Here is what the code will look like:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="recoding.html#cb67-1" tabindex="-1"></a>anes2024<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="recoding.html#cb67-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ideology3=</span><span class="fu">recode</span>(ideology, <span class="st">&#39;very liberal&#39;</span><span class="ot">=</span><span class="st">&quot;liberal&quot;</span>, <span class="st">&#39;liberal&#39;</span><span class="ot">=</span><span class="st">&quot;liberal&quot;</span>, <span class="st">&#39;slightly liberal&#39;</span><span class="ot">=</span><span class="st">&quot;liberal&quot;</span>, <span class="st">&#39;slightly conservative&#39;</span><span class="ot">=</span><span class="st">&quot;conservative&quot;</span>, <span class="st">&#39;conservative&#39;</span><span class="ot">=</span><span class="st">&quot;conservative&quot;</span>, <span class="st">&#39;very conservative&#39;</span><span class="ot">=</span><span class="st">&quot;conservative&quot;</span>)) </span></code></pre></div>
<p>There is a lot going on in the above command, so let’s try to break it down:</p>
<pre><code>POST OPERATION DATAFRAME&lt;-PRE OPERATION DATAFRAME %&gt;%
  mutate(NEW VARIABLE NAME=recode(OLD VARIABLE NAME, 
  ‘OLD VARIABLE VALUE #1’=&quot;NEW VARIABLE VALUE #1&quot;, 
  ‘OLD VARIABLE VALUE #2’=&quot;NEW VARIABLE VALUE #2&quot;,…)) </code></pre>
<p>Using mutate and recode together, we are generating a new version of our dataframe that has a new variable whose values are based on another variable. I have an important piece of advice when using this kind of command: <strong>be sure to copy and paste variable names and values from your Console screen to your script file, because it is very easy to make a typographical error when transcribing variable names and values.</strong> Even if you are careful, there will be times when you make an error in your code and R sends you an error message. Most of the time, you will be able to quickly figure out the source of your error, but if you ever cannot, please feel free to ask your instructor! Sometimes, you will realize that your error modified the dataframe in ways that you don’t like. In that case, you can go back to the original dataframe. If you were using anes2024, you can use this command to restore that dataframe:</p>
<pre><code>load(&quot;Data/anes2024.Rda&quot;) </code></pre>
<p>Or, if that command doesn’t work for you, you can follow the instructions in section <a href="getting-started.html#wont-load">1.6</a> to reload the original dataframe.</p>
<p>To confirm that our recode worked, we can run “table” on both our old and our new variable, like this:</p>
<pre><code>table(anes2024$ideology)
table(anes2024$ideology3)</code></pre>
<p>When run each of these commands, you can see that our recoding worked. You should have have 1187 moderates in each variable. And, if we add the numbers of very liberal, liberal, and slightly liberal respondents (which we can do in R!), we can see that 250+819+543=1612. The same is also true with the conservatives.</p>
<p>What if we were interested in examining the horseshoe theory – that people on the extremely left and extreme right have some major things in common? In that case, we might want to generate a new variable which measures whether or not someone is an extremist. To do that, we could do another version of the mutate/recode command like we did above. But that would require us to type all seven values of our original variable into our code again, which takes a little while. Instead, we could also use the “.default” qualifier to tell R: assign this value to all other cases. Here is how that code would look:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="recoding.html#cb71-1" tabindex="-1"></a>anes2024<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span>   </span>
<span id="cb71-2"><a href="recoding.html#cb71-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">extremist=</span><span class="fu">recode</span>(ideology, <span class="st">&#39;very liberal&#39;</span><span class="ot">=</span><span class="st">&quot;extremist&quot;</span>,</span>
<span id="cb71-3"><a href="recoding.html#cb71-3" tabindex="-1"></a>                          <span class="st">&#39;very conservative&#39;</span><span class="ot">=</span><span class="st">&quot;extremist&quot;</span>, </span>
<span id="cb71-4"><a href="recoding.html#cb71-4" tabindex="-1"></a>                          <span class="at">.default=</span><span class="st">&quot;not extremist&quot;</span>))</span></code></pre></div>
<p>Now, when we run the command:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="recoding.html#cb72-1" tabindex="-1"></a><span class="fu">table</span>(anes2024<span class="sc">$</span>extremist)</span></code></pre></div>
<pre><code>## 
##     extremist not extremist 
##           559          4173</code></pre>
<p>we can see that we successfully created our new variable.</p>
</div>
<div id="reverse-ord" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Reversing the order of ordinal variables<a href="recoding.html#reverse-ord" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ordered factors in R have “levels” that are always displayed in the same order (it might be helpful to think of them as going from low to high). To see the levels of the ANES’s ideology variable, we can use this command:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="recoding.html#cb74-1" tabindex="-1"></a><span class="fu">levels</span>(anes2024<span class="sc">$</span>ideology)</span></code></pre></div>
<pre><code>## [1] &quot;very liberal&quot;          &quot;liberal&quot;              
## [3] &quot;slightly liberal&quot;      &quot;moderate&quot;             
## [5] &quot;slightly conservative&quot; &quot;conservative&quot;         
## [7] &quot;very conservative&quot;</code></pre>
<p>The output after this command shows that the variable is set up so that “very liberal” is the “lowest” value (it comes first in the list), and “very conservative” is the “highest” value (it comes last in the list). However, what if we were writing a paper that focused on liberals and liberalism? In that case, we might want an ideology variable which treated these values in the opposite order, so that “very liberal” is the highest value on our scale. Here is how we would create a new ordered factor called “liberalism” which is the ideology variable reversed:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="recoding.html#cb76-1" tabindex="-1"></a><span class="co">#first we create a vector called v which is the levels of our ideology variable</span></span>
<span id="cb76-2"><a href="recoding.html#cb76-2" tabindex="-1"></a>v<span class="ot">&lt;-</span><span class="fu">levels</span>(anes2024<span class="sc">$</span>ideology) </span>
<span id="cb76-3"><a href="recoding.html#cb76-3" tabindex="-1"></a></span>
<span id="cb76-4"><a href="recoding.html#cb76-4" tabindex="-1"></a><span class="co">#second we reverse the order of v, telling R to make the largest value the smallest and the smallest the largest</span></span>
<span id="cb76-5"><a href="recoding.html#cb76-5" tabindex="-1"></a>v<span class="ot">&lt;-</span>v[<span class="fu">length</span>(v)<span class="sc">:</span><span class="dv">1</span>]</span>
<span id="cb76-6"><a href="recoding.html#cb76-6" tabindex="-1"></a></span>
<span id="cb76-7"><a href="recoding.html#cb76-7" tabindex="-1"></a><span class="co">#third, we use reorder to generate a new factor called liberalism with the opposite levels as our ideology variable </span></span>
<span id="cb76-8"><a href="recoding.html#cb76-8" tabindex="-1"></a>anes2024<span class="sc">$</span>liberalism<span class="ot">&lt;-</span><span class="fu">reorder</span>(anes2024<span class="sc">$</span>ideology,<span class="at">new.order=</span>v)</span>
<span id="cb76-9"><a href="recoding.html#cb76-9" tabindex="-1"></a></span>
<span id="cb76-10"><a href="recoding.html#cb76-10" tabindex="-1"></a><span class="co">#finally, we can remove our vector v, since we don&#39;t need it anymore</span></span>
<span id="cb76-11"><a href="recoding.html#cb76-11" tabindex="-1"></a><span class="fu">rm</span>(v)</span></code></pre></div>
<p>To make sure that your new variable worked, you can enter <code>table(anes2024$ideology)</code> and <code>table(anes2024$liberalism)</code> into your console and see that both variables have 309 people that called themselves “very conservative” and 250 that called themselves “very liberal.”</p>
</div>
<div id="factor-as-numeric" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Making ordinal variables numeric<a href="recoding.html#factor-as-numeric" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sometimes you might want to make an ordered factors a number that you can analyze mathematically. So, for example, let’s imagine that we wanted to be able to think of the liberalism variable that we just generated as a number rather than the words “very conservative,” “conservative,” etc. R makes this very easy to do, with the code “as.numeric.” You can make a variable called liberalism.n like this:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="recoding.html#cb77-1" tabindex="-1"></a>anes2024<span class="sc">$</span>liberalism.n<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(anes2024<span class="sc">$</span>liberalism)</span></code></pre></div>
<p>That code generates a new variable called liberalism.n with values from 1 (which we know from the levels of our liberalism variable means “very conservative”) to 7 (which means “very liberal”). This variable will be slightly easier to deal with in future chapters if the lowest item on the scale is 0, instead of 1. So, to make that happen, we can ask R to subtract one from every value of the liberalism.n variable like this:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="recoding.html#cb78-1" tabindex="-1"></a>anes2024<span class="sc">$</span>liberalism.n<span class="ot">&lt;-</span>anes2024<span class="sc">$</span>liberalism.n<span class="dv">-1</span></span></code></pre></div>
<p>Now if you run <code>table(anes2024$liberalism.n)</code>, you will see that your new variable has values ranging from 0 to 6, and that the number of cases with each value is the same as they are in the liberalism variable.</p>
</div>
<div id="recode-dummy" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Dealing with variables coded 0/1<a href="recoding.html#recode-dummy" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When looking at data in the real world, we will often find variables coded with only two possible values – 0 or 1. These variables are sometimes called dummy variables or binary variables. In general, these variables are used to mean the presence or absence of some characteristic. For example, either someone is married (1), or they are not (0). Either a country is a democracy (1) or it is not (0). On the anes2024 dataframe, I have coded the variable “female” in this way. If you refer to the codebook, you can see that 0 means male and 1 means female. It will be useful mathematically to have it coded this way in future labs. But it will be less useful when generating graphics, since the “1” and “0”s produced on the axis and in the legends will not be that informative. So, we may want to generate a “sex” variable that uses words instead of numbers. We can do so with this code:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="recoding.html#cb79-1" tabindex="-1"></a>anes2024<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="recoding.html#cb79-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex=</span><span class="fu">recode</span>(female, <span class="st">&#39;1&#39;</span><span class="ot">=</span><span class="st">&quot;female&quot;</span>,<span class="st">&#39;0&#39;</span><span class="ot">=</span><span class="st">&quot;male&quot;</span>))</span></code></pre></div>
<p>We can check our results with this code (we could also use tab1 instead of table here).:</p>
<pre><code>table(anes2024$female)
table(anes2024$sex)</code></pre>
<p>You should see that R reports the same number as 1s with the old “female” variable” as it does “female” with the new “sex” variable. and the same should be true of 0s and “male”.</p>
</div>
<div id="simp-int" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Simplifying interval variables<a href="recoding.html#simp-int" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="cut-2" class="section level3 hasAnchor" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Simplifying interval variables using cut2()<a href="recoding.html#cut-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Interval variables give us a lot of information, and it is sometimes too much! For example, we might want to generate a graph comparing age groups, rather than a graph of individuals at each age between 18 and 80. This is where the cut2() command from the Hmisc package can come in handy. Let’s say we want to create three roughly evenly distributed age groups. We can use cut2 like this:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="recoding.html#cb81-1" tabindex="-1"></a>anes2024<span class="sc">$</span>age3<span class="ot">&lt;-</span><span class="fu">cut2</span>(anes2024<span class="sc">$</span>age, <span class="at">g=</span><span class="dv">3</span>)</span></code></pre></div>
<p>The g=3 is telling R to divide age into three roughly equal groups and make them into a new variable called age3. If we wanted 4 groups, or 2 groups, or 5 groups, we could just change that number. Now let’s run table() on our new variable:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="recoding.html#cb82-1" tabindex="-1"></a><span class="fu">table</span>(anes2024<span class="sc">$</span>age3)</span></code></pre></div>
<pre><code>## 
## [18,44) [44,65) [65,80] 
##    1779    1772    1691</code></pre>
<p>This output is telling us that our new variable has three values—[18,44), [42,65), and [65,80]. This notation means that the first group has 18-year-olds to those younger than 44 (that is what the “)” means), the second group has 42-year-olds to those younger than 65 (again, we learn this from the closed parenthesis), and the third group has 65-year-olds and older. We could use mutate(recode()) on those value names, like we did above, but here is an easier solution. The cut2 command generates an ordered factor, which is how R likes to treat ordinal variables. Let’s take a look at the levels of our new age variable:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="recoding.html#cb84-1" tabindex="-1"></a><span class="fu">levels</span>(anes2024<span class="sc">$</span>age3)</span></code></pre></div>
<pre><code>## [1] &quot;[18,44)&quot; &quot;[44,65)&quot; &quot;[65,80]&quot;</code></pre>
<p>This output means that [18,44) is the “low” level of the new age3 variable, [44,65) is the medium level, and [65,80] is the high level. To rename those variables, we can just make a list using the c() command that we learned in lab 1, like this:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="recoding.html#cb86-1" tabindex="-1"></a><span class="fu">levels</span>(anes2024<span class="sc">$</span>age3)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">&quot;young&quot;</span>, <span class="st">&quot;middle aged&quot;</span>, <span class="st">&quot;old&quot;</span>)</span></code></pre></div>
<p>When we run that command, R renames the levels of our age3 variable. When renaming the levels of a variable, be sure to list the new levels in an order that corresponds with the previous levels of the variable. If you typed “old” first, in the command below, you would be telling R to call people from 18-44 old, and you would also make “old” the lowest level of your age3 variable.</p>
<p>To confirm that this worked, you can type</p>
<pre><code>table(anes2024$age3)</code></pre>
<p>and you should see your new labels.</p>
</div>
<div id="case-when" class="section level3 hasAnchor" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Simplifying interval variables with case_when<a href="recoding.html#case-when" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In section <a href="recoding.html#simp-int">4.6</a> we learned how to use the cut2 command to divide interval variables into groups of roughly the same size. But what if we are interested in separating interval variables into groups above or below specific values? For example. we might be interested in looking at people in their teens, in their 20s, in their 30s, etc. To do that, we can write the following:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="recoding.html#cb88-1" tabindex="-1"></a>anes2024<span class="ot">&lt;-</span>anes2024 <span class="sc">%&gt;%</span> </span>
<span id="cb88-2"><a href="recoding.html#cb88-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_groups=</span><span class="fu">case_when</span>(age <span class="sc">%in%</span> <span class="dv">18</span><span class="sc">:</span><span class="dv">19</span> <span class="sc">~</span> <span class="st">&quot;teens&quot;</span>,</span>
<span id="cb88-3"><a href="recoding.html#cb88-3" tabindex="-1"></a>          age <span class="sc">%in%</span> <span class="dv">20</span><span class="sc">:</span><span class="dv">29</span>  <span class="sc">~</span> <span class="st">&quot;20s&quot;</span>,</span>
<span id="cb88-4"><a href="recoding.html#cb88-4" tabindex="-1"></a>          age <span class="sc">%in%</span> <span class="dv">30</span><span class="sc">:</span><span class="dv">39</span>  <span class="sc">~</span> <span class="st">&quot;30s&quot;</span>, </span>
<span id="cb88-5"><a href="recoding.html#cb88-5" tabindex="-1"></a>          age <span class="sc">%in%</span> <span class="dv">40</span><span class="sc">:</span><span class="dv">49</span>  <span class="sc">~</span> <span class="st">&quot;40s&quot;</span>, </span>
<span id="cb88-6"><a href="recoding.html#cb88-6" tabindex="-1"></a>          age <span class="sc">%in%</span> <span class="dv">50</span><span class="sc">:</span><span class="dv">59</span>  <span class="sc">~</span> <span class="st">&quot;50s&quot;</span>, </span>
<span id="cb88-7"><a href="recoding.html#cb88-7" tabindex="-1"></a>          age <span class="sc">%in%</span> <span class="dv">60</span><span class="sc">:</span><span class="dv">69</span>  <span class="sc">~</span> <span class="st">&quot;60s&quot;</span>, </span>
<span id="cb88-8"><a href="recoding.html#cb88-8" tabindex="-1"></a>          age <span class="sc">%in%</span> <span class="dv">70</span><span class="sc">:</span><span class="dv">80</span>  <span class="sc">~</span> <span class="st">&quot;over 70&quot;</span>))</span></code></pre></div>
<p>This code uses mutate, which we first saw in section <a href="recoding.html#recode-nom">4.2</a>, to create a new variable called age_groups. We set the values for our new variable with a new command that is available through the tidyverse package, case_when(). This command lets us create variable values based on ranges of numbers from our old variable (which we identify with the %in% and colons between the values).</p>
<p>We can take a look at our new variable using table, as follows:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="recoding.html#cb89-1" tabindex="-1"></a><span class="fu">table</span>(anes2024<span class="sc">$</span>age_groups)</span></code></pre></div>
<pre><code>## 
##     20s     30s     40s     50s     60s over 70   teens 
##     500     841     874     802    1014    1162      49</code></pre>
<p>You might notice that the values for our new variable are listed in a strange order, with 20s first and teens last. This is because our new variable is a character variable, and the values are thus listed in in alphabetical order.</p>
<p>To fix this, we can make our new variable into an ordered factors and set the levels from youngest to oldest like this:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="recoding.html#cb91-1" tabindex="-1"></a>anes2024<span class="sc">$</span>age_groups<span class="ot">&lt;-</span><span class="fu">ordered</span>(anes2024<span class="sc">$</span>age_groups, </span>
<span id="cb91-2"><a href="recoding.html#cb91-2" tabindex="-1"></a>        <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;teens&quot;</span>,<span class="st">&quot;20s&quot;</span>,<span class="st">&quot;30s&quot;</span>,<span class="st">&quot;40s&quot;</span>,<span class="st">&quot;50s&quot;</span>,<span class="st">&quot;60s&quot;</span>,<span class="st">&quot;over 70&quot;</span>))</span></code></pre></div>
<p>Now when we enter <code>table(anes2024$age_groups)</code> into the Console we can see the variable values listed in a way that makes more sense. This will also be useful when making tables and graphs.</p>
</div>
</div>
<div id="cross-tabs" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Cross-tabulation tables<a href="recoding.html#cross-tabs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="generating-cross-tabs" class="section level3 hasAnchor" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Generating cross-tabs<a href="recoding.html#generating-cross-tabs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Up until now, we have focused on one single variable at a time. This is an essential component of social scientific analysis. However, most of the questions that we are interested in are about the relationship between two or more variables. The rest of the work that we will do in R from this point forward will be geared toward helping us to make observations and inferences about the relationship between more than one variable.</p>
<p>One way that we can start to examine the relationship between more than one variable is by making cross-tabulation tables (often called crosstabs). These are essentially two frequency tables presented in a table. Crosstabs are most useful when looking at the relationship between twp ordinal or nominal variables. For example, let’s look at the relationship between education and income in the anes2024 dataframe. We can hypothesize that people with more education will make more income. To test this, we can first use the xtabs() command, like this:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="recoding.html#cb92-1" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024)</span></code></pre></div>
<pre><code>##                       education
## income                 less than high school high school some college
##   under $9,999                            81         137          131
##   $10,000 to $29,999                      65         156          239
##   $30,000 to $59,999                      57         271          387
##   $60,000 to $99,999                      33         191          391
##   $100,000 to $249,999                    19         131          423
##   $250,000 or more                         1          22           70
##                       education
## income                  ba graduate degree
##   under $9,999          68              47
##   $10,000 to $29,999    68              25
##   $30,000 to $59,999   205              98
##   $60,000 to $99,999   297             188
##   $100,000 to $249,999 548             488
##   $250,000 or more     110             188</code></pre>
<p>Let’s break down how we used this command: we put the <strong>dependent variable</strong>, income, first, and then the <strong>independent variable</strong>, education, second. Crosstabs generally have the independent variable in columns and the dependent variable in rows. This setup lets us do that.</p>
</div>
<div id="adding-column-totals-to-cross-tabs" class="section level3 hasAnchor" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> Adding column totals to cross-tabs<a href="recoding.html#adding-column-totals-to-cross-tabs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The output that our command generated is a basic crosstab. It tells us that 81 people with less than a high school education make under $9,999 per year, 65 people with less than a high school education make $10,000-29,999, etc. Now we might be tempted to look at this and say: “Graduate school is a waste of time! 488 people from our sample with graduate degrees make $100,000 to $250,000, while 548 people a BA make $100,000 to $250,000.” However, that would be a mistake! To understand why, we should look at the column totals from our crosstab, which we can produce with this command:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="recoding.html#cb94-1" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024)) </span></code></pre></div>
<pre><code>##                       education
## income                 less than high school high school some college
##   under $9,999                            81         137          131
##   $10,000 to $29,999                      65         156          239
##   $30,000 to $59,999                      57         271          387
##   $60,000 to $99,999                      33         191          391
##   $100,000 to $249,999                    19         131          423
##   $250,000 or more                         1          22           70
##   Sum                                    256         908         1641
##                       education
## income                   ba graduate degree  Sum
##   under $9,999           68              47  464
##   $10,000 to $29,999     68              25  553
##   $30,000 to $59,999    205              98 1018
##   $60,000 to $99,999    297             188 1100
##   $100,000 to $249,999  548             488 1609
##   $250,000 or more      110             188  391
##   Sum                  1296            1034 5135</code></pre>
</div>
<div id="column-percents" class="section level3 hasAnchor" number="4.7.3">
<h3><span class="header-section-number">4.7.3</span> Adding column percents to cross-tabs<a href="recoding.html#column-percents" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Take a look at the above column totals. Our anes2024 dataframe has 1,034 people with graduate degrees, while it has 1,296 people with BAs. So, returning to those two numbers from above, the 488 people with graduate degrees with household incomes of $100,000 to $250,000 make up 47.2% of all of graduate degree holders in our sample (because 488/1034=.472), while the 548 people with BAs with household incomes of $100,000 to $250,000 make up only 42.3% of all of the people with some college in our sample (because 528/1296=.423). In other words, there is a larger proportion of people with graduate degrees with household incomes of $100,000 to $250,000 than people with BAs with household incomes of $100,000 to $250,000. <strong>Thus, when interpreting crosstabs it is important to look at the column percents, and not just the raw numbers.</strong> To make R generate all of the column percents in a crosstab at the same time, we can use the colPerc() command from the tigerstats package that we installed for today. We can enter this command:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="recoding.html#cb96-1" tabindex="-1"></a><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024))</span></code></pre></div>
<pre><code>##                       education
## income                 less than high school high school some college
##   under $9,999                         31.64       15.09         7.98
##   $10,000 to $29,999                   25.39       17.18        14.56
##   $30,000 to $59,999                   22.27       29.85        23.58
##   $60,000 to $99,999                   12.89       21.04        23.83
##   $100,000 to $249,999                  7.42       14.43        25.78
##   $250,000 or more                      0.39        2.42         4.27
##   Total                               100.00      100.00       100.00
##                       education
## income                     ba graduate degree
##   under $9,999           5.25            4.55
##   $10,000 to $29,999     5.25            2.42
##   $30,000 to $59,999    15.82            9.48
##   $60,000 to $99,999    22.92           18.18
##   $100,000 to $249,999  42.28           47.20
##   $250,000 or more       8.49           18.18
##   Total                100.00          100.00</code></pre>
<p><strong>Remember when interpreting this output that the numbers are now the column percents, not the raw numbers.</strong> If you take a look at this output, you will see that people with more education seem to make more money. If you look at the top income category row (for those with household incomes of $250,000 or more, the percent of thsoe at the lowest education level, “less than high school” in that income category is 0.39%, and as the education level increases this percent increase to 2.42%, 4.27%, 8.49%, and 18,18% for those with graduate degrees.</p>
</div>
<div id="export-crosstabs" class="section level3 hasAnchor" number="4.7.4">
<h3><span class="header-section-number">4.7.4</span> Exporting cross-tabs for your word processor<a href="recoding.html#export-crosstabs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you have been following along, the cross-tabs that you have generated have shown up reasonably neatly in the Console of R-Studio. But often, you will want to export those tables into a format that you can easily bring into your word processor so that you can refer to it in papers that you are writing. To do this, you first want to give the cross tab you want to export a name as an object, like this:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="recoding.html#cb98-1" tabindex="-1"></a>ctab1<span class="ot">&lt;-</span><span class="fu">colPerc</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>income<span class="sc">+</span>education, <span class="at">data=</span>anes2024))</span></code></pre></div>
<p>That command creates a new object called “ctab1.” If you paste <code>ctab1</code> into your Console and hit enter, you will see that same crosstab that you made in section <a href="recoding.html#column-percents">4.7.3</a>.</p>
<p>Before exporting this crosstab, you have to make two changes to it in order for the export command that we will use to work. You need to change it to a dataframe, and you need to set the row names (which are currently the different income levels) as a column. To do both of those things, you can run this command:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="recoding.html#cb99-1" tabindex="-1"></a>ctab1<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(ctab1)<span class="sc">%&gt;%</span><span class="fu">rownames_to_column</span>(<span class="st">&quot;income&quot;</span>)</span></code></pre></div>
<p>Now your “ctab1” is formatted to be exported nicely (when you use this with other tables, just rename the text in quotes after “rownames_to_columns” to fit what you’d like to call your rownames). To export this, run this command:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="recoding.html#cb100-1" tabindex="-1"></a><span class="fu">flextable</span>(ctab1) <span class="sc">%&gt;%</span> <span class="fu">save_as_docx</span>(<span class="at">path=</span><span class="st">&quot;ctab1.docx&quot;</span>)</span></code></pre></div>
<p>This has created a file called “ctab1.docx” in the main folder where you have your Scope and Methods labs (the folder that you created in section <a href="getting-started.html#class-project">1.2</a>). You can open that file in Microsoft Word, or you can pull it into a Pages file or a Google Document. If you’d rather export your table into a rich text format file, you can use <code>save_as_rtf</code> instead of <code>save_as_docx</code> in the above command.</p>
</div>
</div>
<div id="mean-comparison-tables" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> Mean comparison tables<a href="recoding.html#mean-comparison-tables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Crosstabs are useful when we have two nominal or ordinal variables. But what if we want to look at the relationship between a nominal or ordinal variable and an interval variable? In that case, a mean comparison table can be helpful. The tidyverse has some commands that we can use to generate such a table. To demonstrate, let’s look at our states2025 dataframe, and the relationship between the region variable and the govApproval2024 variable (which measures the proportion of the population that approved of a state’s governor in 2024). The first thing that we need to learn is the group_by() command. This tells R: “make groups based on the variable that we tell you.” In our case, we want to make groups based on our independent variable (which, for now, must be ordinal or nominal). Once we have done that, we can use the summarise() command to get the mean. For good measure, we can also use the summarise() command to calculate the standard deviation as well as the size of each group. Here is what that command looks like:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="recoding.html#cb101-1" tabindex="-1"></a>states2025 <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="recoding.html#cb101-2" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb101-3"><a href="recoding.html#cb101-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(govApproval2024), <span class="at">sd=</span><span class="fu">sd</span>(govApproval2024), <span class="at">n=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 4 × 4
##   region      mean      sd     n
##   &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;
## 1 midwest    0.348  0.0553    12
## 2 northeast  0.388  0.0545     9
## 3 south     NA     NA         17
## 4 west       0.335  0.0380    13</code></pre>
<p>We can see that, in the mean midwest state, .348 (or 34.8%) of the population approved of the governor, with a standard deviation of .0553, and .388 of the population of the mean northeast state (or 38.8% approved of the government) approved of the governor, with a standard deviation of .0545. The reason that the South is NA is because there is a Southern “state” without a governor – the District of Columbia not technically a state). To filter out states without data on that variable, we can add another line to our command: filter(!is.na(govApproval2024))%&gt;% (we used a version of this command in section <a href="graphing.html#bar-graph-nominal">3.2.1</a>). Our new command looks like this:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="recoding.html#cb103-1" tabindex="-1"></a>states2025 <span class="sc">%&gt;%</span> </span>
<span id="cb103-2"><a href="recoding.html#cb103-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(govApproval2024)) <span class="sc">%&gt;%</span> </span>
<span id="cb103-3"><a href="recoding.html#cb103-3" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb103-4"><a href="recoding.html#cb103-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(govApproval2024), <span class="at">sd=</span><span class="fu">sd</span>(govApproval2024), <span class="at">n=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 4 × 4
##   region     mean     sd     n
##   &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
## 1 midwest   0.348 0.0553    12
## 2 northeast 0.388 0.0545     9
## 3 south     0.347 0.0597    16
## 4 west      0.335 0.0380    13</code></pre>
<p>Now we can see that northeast states seem to have the highest approval of their governors, and also that there is no region where the majority of people approve of the governor in the average state.</p>
<p>To export this table so that we can easily pull it into our word processor, we can do something similar to what we did in section <a href="recoding.html#export-crosstabs">4.7.4</a>. However, it is easier to export a mean comparison table because we don’t have to first tell R to treat it as a dataframe. You can export the file with the following code:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="recoding.html#cb105-1" tabindex="-1"></a>mc1<span class="ot">&lt;-</span>states2025 <span class="sc">%&gt;%</span> </span>
<span id="cb105-2"><a href="recoding.html#cb105-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(govApproval2024)) <span class="sc">%&gt;%</span> </span>
<span id="cb105-3"><a href="recoding.html#cb105-3" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb105-4"><a href="recoding.html#cb105-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(govApproval2024), <span class="at">sd=</span><span class="fu">sd</span>(govApproval2024), <span class="at">n=</span><span class="fu">n</span>())</span>
<span id="cb105-5"><a href="recoding.html#cb105-5" tabindex="-1"></a><span class="fu">flextable</span>(mc1) <span class="sc">%&gt;%</span> <span class="fu">save_as_docx</span>(<span class="at">path=</span><span class="st">&quot;mc1.docx&quot;</span>)</span></code></pre></div>
<p>Now you should see a file called “mc1.docx” in the main folder where you have your Scope and Methods labs (the folder that you created in section <a href="getting-started.html#class-project">1.2</a>).</p>
</div>
<div id="review-of-this-chapters-commands-3" class="section level2 hasAnchor" number="4.9">
<h2><span class="header-section-number">4.9</span> Review of this chapter’s commands<a href="recoding.html#review-of-this-chapters-commands-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table style="width:100%;">
<colgroup>
<col width="8%" />
<col width="83%" />
<col width="7%" />
</colgroup>
<thead>
<tr>
<th align="left">Command</th>
<th align="left">Purpose</th>
<th align="left">Library</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">mutate(recode())</td>
<td align="left">A set of commands to rename the values of variables.</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
<tr>
<td align="left">cut2()</td>
<td align="left">Turn an interval variable into an ordinal variable. Remember to specify “g=” to tell R how many groups to split your variable into.</td>
<td align="left">Hmisc</td>
</tr>
<tr>
<td align="left">levels()</td>
<td align="left">You can use this command to see the levels of an ordered factor, or you can also use it to assign new levels to an ordered factor, like this: levels(df$variable&lt;-c(“new level1”,“new level2”,…)</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">reorder()</td>
<td align="left">You can use this command to change the order of levels in an ordered factor</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">as.numeric</td>
<td align="left">You can use this command to make a factor into a numeric variable, like this: df$NewVariable&lt;-as.numeric(df$Variable)</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">case_when()</td>
<td align="left">You can use this command along with mutate() and %in% to assign ranges of an interval variable to a new value of a new variable</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
<tr>
<td align="left">ordered</td>
<td align="left">you can use this command to make a variable into an ordered factor</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">xtabs()</td>
<td align="left">Makes a crosstab table with raw values. Remember to define variables like this: xtabs(~DV+IV, data=DATAFRAME)</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">addmargins(xtabs())</td>
<td align="left">Makes a crosstab table with row and column totals.</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">colPerc(xtabs())</td>
<td align="left">Makes a crosstab table with column percents. Useful for making comparisons.</td>
<td align="left">tigerstats</td>
</tr>
<tr>
<td align="left">flextable</td>
<td align="left">You can use this with %&gt;% save_as_docx(path=“…”) to export your tables for word processors</td>
<td align="left">flextable</td>
</tr>
<tr>
<td align="left">group_by()</td>
<td align="left">A dplyr command that is useful when summarizing a dataframe according to a nominal or ordinal variable. Usually used with the “pipe” (%&gt;%).</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
<tr>
<td align="left">summarise()</td>
<td align="left">A dplyr command that is useful when summarizing a dataframe according to a nominal or ordinal variable. Usually used with the “pipe” (%&gt;%).</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="graphing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="making-controlled-comparisons.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/04_recoding.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
