<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Welcome to the tidyverse | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</title>
  <meta name="description" content="This is the preface of the workbook" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Welcome to the tidyverse | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the preface of the workbook" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Welcome to the tidyverse | Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0" />
  
  <meta name="twitter:description" content="This is the preface of the workbook" />
  

<meta name="author" content="Michael Strausz" />


<meta name="date" content="2025-08-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="getting-started.html"/>
<link rel="next" href="graphing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Are You Ready for R?</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="whats-new-in-version-3.html"><a href="whats-new-in-version-3.html"><i class="fa fa-check"></i>What’s new in version 3.0?</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#why-r"><i class="fa fa-check"></i><b>1.1</b> Why R?</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#class-project"><i class="fa fa-check"></i><b>1.2</b> Create a project for this class</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#add-files"><i class="fa fa-check"></i><b>1.3</b> Add the course files to your project</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#using-the-console"><i class="fa fa-check"></i><b>1.4</b> Using the Console</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="getting-started.html"><a href="getting-started.html#rules-about-naming-objects"><i class="fa fa-check"></i><b>1.4.1</b> Rules about naming objects</a></li>
<li class="chapter" data-level="1.4.2" data-path="getting-started.html"><a href="getting-started.html#common-practices-when-naming-objects"><i class="fa fa-check"></i><b>1.4.2</b> Common practices when naming objects</a></li>
<li class="chapter" data-level="1.4.3" data-path="getting-started.html"><a href="getting-started.html#about-vectors"><i class="fa fa-check"></i><b>1.4.3</b> About vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#first-script"><i class="fa fa-check"></i><b>1.5</b> Writing your first R script</a></li>
<li class="chapter" data-level="1.6" data-path="getting-started.html"><a href="getting-started.html#wont-load"><i class="fa fa-check"></i><b>1.6</b> What do to if the “load” command doesn’t load the dataframe</a></li>
<li class="chapter" data-level="1.7" data-path="getting-started.html"><a href="getting-started.html#review-of-this-chapters-commands"><i class="fa fa-check"></i><b>1.7</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>2</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tidyverse.html"><a href="tidyverse.html#install-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Installing packages</a></li>
<li class="chapter" data-level="2.2" data-path="tidyverse.html"><a href="tidyverse.html#exploring"><i class="fa fa-check"></i><b>2.2</b> Exploring dataframes</a></li>
<li class="chapter" data-level="2.3" data-path="tidyverse.html"><a href="tidyverse.html#org-script"><i class="fa fa-check"></i><b>2.3</b> Organizing your scripts</a></li>
<li class="chapter" data-level="2.4" data-path="tidyverse.html"><a href="tidyverse.html#welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>2.4</b> Welcome to the tidyverse</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="tidyverse.html"><a href="tidyverse.html#introducing-the-pipe-in-tidyverse"><i class="fa fa-check"></i><b>2.4.1</b> Introducing the ‘pipe’ in tidyverse</a></li>
<li class="chapter" data-level="2.4.2" data-path="tidyverse.html"><a href="tidyverse.html#select-in-tidyverse"><i class="fa fa-check"></i><b>2.4.2</b> select() in tidyverse</a></li>
<li class="chapter" data-level="2.4.3" data-path="tidyverse.html"><a href="tidyverse.html#a-warning-about-the-select-command"><i class="fa fa-check"></i><b>2.4.3</b> A warning about the select() command</a></li>
<li class="chapter" data-level="2.4.4" data-path="tidyverse.html"><a href="tidyverse.html#arrange-in-tidyverse"><i class="fa fa-check"></i><b>2.4.4</b> arrange() in tidyverse</a></li>
<li class="chapter" data-level="2.4.5" data-path="tidyverse.html"><a href="tidyverse.html#glimpse-in-tidyverse"><i class="fa fa-check"></i><b>2.4.5</b> glimpse() in tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tidyverse.html"><a href="tidyverse.html#review-of-this-chapters-commands-1"><i class="fa fa-check"></i><b>2.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>3</b> Graphing and describing variables</a>
<ul>
<li class="chapter" data-level="3.1" data-path="graphing.html"><a href="graphing.html#getting-started-tidyverse"><i class="fa fa-check"></i><b>3.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="graphing.html"><a href="graphing.html#start-graphing"><i class="fa fa-check"></i><b>3.2</b> Getting started with ggplot and graphing</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="graphing.html"><a href="graphing.html#bar-graph-nominal"><i class="fa fa-check"></i><b>3.2.1</b> Bar graphing a nominal variable</a></li>
<li class="chapter" data-level="3.2.2" data-path="graphing.html"><a href="graphing.html#remove-na"><i class="fa fa-check"></i><b>3.2.2</b> Removing the NA bar</a></li>
<li class="chapter" data-level="3.2.3" data-path="graphing.html"><a href="graphing.html#add-return"><i class="fa fa-check"></i><b>3.2.3</b> Adding a second line to a graph’s title</a></li>
<li class="chapter" data-level="3.2.4" data-path="graphing.html"><a href="graphing.html#saving-a-graph"><i class="fa fa-check"></i><b>3.2.4</b> Saving a graph</a></li>
<li class="chapter" data-level="3.2.5" data-path="graphing.html"><a href="graphing.html#bar-graph-ordinal"><i class="fa fa-check"></i><b>3.2.5</b> Bar graphing an ordinal variable</a></li>
<li class="chapter" data-level="3.2.6" data-path="graphing.html"><a href="graphing.html#what-to-do-about-overlapping-labels"><i class="fa fa-check"></i><b>3.2.6</b> What to do about overlapping labels</a></li>
<li class="chapter" data-level="3.2.7" data-path="graphing.html"><a href="graphing.html#histogram"><i class="fa fa-check"></i><b>3.2.7</b> Generating a histogram</a></li>
<li class="chapter" data-level="3.2.8" data-path="graphing.html"><a href="graphing.html#removing-scientific-notation-from-axes"><i class="fa fa-check"></i><b>3.2.8</b> Removing scientific notation from axes</a></li>
<li class="chapter" data-level="3.2.9" data-path="graphing.html"><a href="graphing.html#adjusting-bin-width-on-a-histogram"><i class="fa fa-check"></i><b>3.2.9</b> Adjusting bin width on a histogram</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion"><i class="fa fa-check"></i><b>3.3</b> Central tendancy and dispersion</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-nominal-variables"><i class="fa fa-check"></i><b>3.3.1</b> Central tendency and dispersion of nominal variables</a></li>
<li class="chapter" data-level="3.3.2" data-path="graphing.html"><a href="graphing.html#central-tendency-and-dispersion-of-ordinal-variables"><i class="fa fa-check"></i><b>3.3.2</b> Central tendency and dispersion of ordinal variables</a></li>
<li class="chapter" data-level="3.3.3" data-path="graphing.html"><a href="graphing.html#central-tendancy-and-dispersion-of-interval-variables"><i class="fa fa-check"></i><b>3.3.3</b> Central tendancy and dispersion of interval variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="graphing.html"><a href="graphing.html#states-world"><i class="fa fa-check"></i><b>3.4</b> A note on using the states2025 and world2025</a></li>
<li class="chapter" data-level="3.5" data-path="graphing.html"><a href="graphing.html#review-of-this-chapters-commands-2"><i class="fa fa-check"></i><b>3.5</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="recoding.html"><a href="recoding.html"><i class="fa fa-check"></i><b>4</b> Recoding and comparing values of variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="recoding.html"><a href="recoding.html#getting-started-recoding"><i class="fa fa-check"></i><b>4.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="recoding.html"><a href="recoding.html#recode-nom"><i class="fa fa-check"></i><b>4.2</b> Recoding ordinal and nominal variables</a></li>
<li class="chapter" data-level="4.3" data-path="recoding.html"><a href="recoding.html#reverse-ord"><i class="fa fa-check"></i><b>4.3</b> Reversing the order of ordinal variables</a></li>
<li class="chapter" data-level="4.4" data-path="recoding.html"><a href="recoding.html#factor-as-numeric"><i class="fa fa-check"></i><b>4.4</b> Making ordinal variables numeric</a></li>
<li class="chapter" data-level="4.5" data-path="recoding.html"><a href="recoding.html#recode-dummy"><i class="fa fa-check"></i><b>4.5</b> Dealing with variables coded 0/1</a></li>
<li class="chapter" data-level="4.6" data-path="recoding.html"><a href="recoding.html#simp-int"><i class="fa fa-check"></i><b>4.6</b> Simplifying interval variables</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="recoding.html"><a href="recoding.html#cut-2"><i class="fa fa-check"></i><b>4.6.1</b> Simplifying interval variables using cut2()</a></li>
<li class="chapter" data-level="4.6.2" data-path="recoding.html"><a href="recoding.html#case-when"><i class="fa fa-check"></i><b>4.6.2</b> Simplifying interval variables with case_when</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="recoding.html"><a href="recoding.html#cross-tabs"><i class="fa fa-check"></i><b>4.7</b> Cross-tabulation tables</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="recoding.html"><a href="recoding.html#generating-cross-tabs"><i class="fa fa-check"></i><b>4.7.1</b> Generating cross-tabs</a></li>
<li class="chapter" data-level="4.7.2" data-path="recoding.html"><a href="recoding.html#adding-column-totals-to-cross-tabs"><i class="fa fa-check"></i><b>4.7.2</b> Adding column totals to cross-tabs</a></li>
<li class="chapter" data-level="4.7.3" data-path="recoding.html"><a href="recoding.html#column-percents"><i class="fa fa-check"></i><b>4.7.3</b> Adding column percents to cross-tabs</a></li>
<li class="chapter" data-level="4.7.4" data-path="recoding.html"><a href="recoding.html#export-crosstabs"><i class="fa fa-check"></i><b>4.7.4</b> Exporting cross-tabs for your word processor</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="recoding.html"><a href="recoding.html#mean-comparison-tables"><i class="fa fa-check"></i><b>4.8</b> Mean comparison tables</a></li>
<li class="chapter" data-level="4.9" data-path="recoding.html"><a href="recoding.html#review-of-this-chapters-commands-3"><i class="fa fa-check"></i><b>4.9</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html"><i class="fa fa-check"></i><b>5</b> Making controlled comparisons</a>
<ul>
<li class="chapter" data-level="5.1" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#getting-started-comparisons"><i class="fa fa-check"></i><b>5.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="5.2" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#stacked"><i class="fa fa-check"></i><b>5.2</b> Representing crosstabs with stacked bar graphs</a></li>
<li class="chapter" data-level="5.3" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#representing-mean-comparison-tables-with-boxplots"><i class="fa fa-check"></i><b>5.3</b> Representing mean comparison tables with boxplots</a></li>
<li class="chapter" data-level="5.4" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-crosstab"><i class="fa fa-check"></i><b>5.4</b> Adding a control to a crosstab</a></li>
<li class="chapter" data-level="5.5" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#adding-a-control-to-a-mean-comparison-table"><i class="fa fa-check"></i><b>5.5</b> Adding a control to a mean comparison table</a></li>
<li class="chapter" data-level="5.6" data-path="making-controlled-comparisons.html"><a href="making-controlled-comparisons.html#review-of-this-chapters-commands-4"><i class="fa fa-check"></i><b>5.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferences.html"><a href="inferences.html"><i class="fa fa-check"></i><b>6</b> Making inferences from sample means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferences.html"><a href="inferences.html#getting-started-inferences"><i class="fa fa-check"></i><b>6.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="6.2" data-path="inferences.html"><a href="inferences.html#constructing-a-confidence-interval-around-a-mean"><i class="fa fa-check"></i><b>6.2</b> Constructing a confidence interval around a mean</a></li>
<li class="chapter" data-level="6.3" data-path="inferences.html"><a href="inferences.html#ci-around-proportion"><i class="fa fa-check"></i><b>6.3</b> Constructing a confidence interval around a proportion</a></li>
<li class="chapter" data-level="6.4" data-path="inferences.html"><a href="inferences.html#ci-around-proportions"><i class="fa fa-check"></i><b>6.4</b> Constructing confidence intervals around several proportions at once</a></li>
<li class="chapter" data-level="6.5" data-path="inferences.html"><a href="inferences.html#t-test-ind-means"><i class="fa fa-check"></i><b>6.5</b> T-test of independent means</a></li>
<li class="chapter" data-level="6.6" data-path="inferences.html"><a href="inferences.html#caution-about-statistical-significance"><i class="fa fa-check"></i><b>6.6</b> Caution about “statistical significance”</a></li>
<li class="chapter" data-level="6.7" data-path="inferences.html"><a href="inferences.html#t-test-ind-props"><i class="fa fa-check"></i><b>6.7</b> T-test of independent proportions</a></li>
<li class="chapter" data-level="6.8" data-path="inferences.html"><a href="inferences.html#review-of-this-chapters-commands-5"><i class="fa fa-check"></i><b>6.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html"><i class="fa fa-check"></i><b>7</b> From chi-squared to somers’ d</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#getting-started-chi"><i class="fa fa-check"></i><b>7.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="7.2" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#chi-squared"><i class="fa fa-check"></i><b>7.2</b> Calculating chi-squared</a></li>
<li class="chapter" data-level="7.3" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#lambda"><i class="fa fa-check"></i><b>7.3</b> Lambda and the PREs</a></li>
<li class="chapter" data-level="7.4" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#cramers-v"><i class="fa fa-check"></i><b>7.4</b> Cramer’s V</a></li>
<li class="chapter" data-level="7.5" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#somers-d"><i class="fa fa-check"></i><b>7.5</b> Somers’ D</a></li>
<li class="chapter" data-level="7.6" data-path="chi-squared-etc.html"><a href="chi-squared-etc.html#review-of-this-chapters-commands-6"><i class="fa fa-check"></i><b>7.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="pearsons-r.html"><a href="pearsons-r.html"><i class="fa fa-check"></i><b>8</b> Pearson’s r and linear regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="pearsons-r.html"><a href="pearsons-r.html#getting-started-pearsons-r"><i class="fa fa-check"></i><b>8.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="8.2" data-path="pearsons-r.html"><a href="pearsons-r.html#pearsons-r-1"><i class="fa fa-check"></i><b>8.2</b> Pearson’s R</a></li>
<li class="chapter" data-level="8.3" data-path="pearsons-r.html"><a href="pearsons-r.html#scatterplot"><i class="fa fa-check"></i><b>8.3</b> The scatterplot</a></li>
<li class="chapter" data-level="8.4" data-path="pearsons-r.html"><a href="pearsons-r.html#bivariate-regression"><i class="fa fa-check"></i><b>8.4</b> Bivariate linear regression</a></li>
<li class="chapter" data-level="8.5" data-path="pearsons-r.html"><a href="pearsons-r.html#residuals"><i class="fa fa-check"></i><b>8.5</b> Residuals</a></li>
<li class="chapter" data-level="8.6" data-path="pearsons-r.html"><a href="pearsons-r.html#review-of-this-chapters-commands-7"><i class="fa fa-check"></i><b>8.6</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#getting-started-multiple-regression"><i class="fa fa-check"></i><b>9.1</b> Getting started with this chapter</a></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#multiple-regression"><i class="fa fa-check"></i><b>9.2</b> Multiple regression</a></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#residuals-in-multiple-regression"><i class="fa fa-check"></i><b>9.3</b> Residuals in multiple regression</a></li>
<li class="chapter" data-level="9.4" data-path="regression.html"><a href="regression.html#stargazer"><i class="fa fa-check"></i><b>9.4</b> Stargazer output</a></li>
<li class="chapter" data-level="9.5" data-path="regression.html"><a href="regression.html#dummy-variables-in-multiple-regression"><i class="fa fa-check"></i><b>9.5</b> Dummy variables in multiple regression</a></li>
<li class="chapter" data-level="9.6" data-path="regression.html"><a href="regression.html#ordinal-variables-in-regression-analysis"><i class="fa fa-check"></i><b>9.6</b> Ordinal variables in regression analysis</a></li>
<li class="chapter" data-level="9.7" data-path="regression.html"><a href="regression.html#graphing-multiple-regression"><i class="fa fa-check"></i><b>9.7</b> Graphing multiple regression</a></li>
<li class="chapter" data-level="9.8" data-path="regression.html"><a href="regression.html#review-of-this-chapters-commands-8"><i class="fa fa-check"></i><b>9.8</b> Review of this chapter’s commands</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="wild.html"><a href="wild.html"><i class="fa fa-check"></i><b>10</b> R in the wild</a>
<ul>
<li class="chapter" data-level="10.1" data-path="wild.html"><a href="wild.html#todays-lab-as-a-reference"><i class="fa fa-check"></i><b>10.1</b> Today’s lab as a reference</a></li>
<li class="chapter" data-level="10.2" data-path="wild.html"><a href="wild.html#importing-data-into-r"><i class="fa fa-check"></i><b>10.2</b> Importing data into R</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="wild.html"><a href="wild.html#importing-csv-files"><i class="fa fa-check"></i><b>10.2.1</b> Importing CSV files</a></li>
<li class="chapter" data-level="10.2.2" data-path="wild.html"><a href="wild.html#importing-excel-files"><i class="fa fa-check"></i><b>10.2.2</b> Importing Excel files</a></li>
<li class="chapter" data-level="10.2.3" data-path="wild.html"><a href="wild.html#importing-other-files"><i class="fa fa-check"></i><b>10.2.3</b> Importing other files</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="wild.html"><a href="wild.html#cleaning-data-in-r"><i class="fa fa-check"></i><b>10.3</b> Cleaning data in R</a></li>
<li class="chapter" data-level="10.4" data-path="wild.html"><a href="wild.html#resources"><i class="fa fa-check"></i><b>10.4</b> Online R resources</a></li>
<li class="chapter" data-level="10.5" data-path="wild.html"><a href="wild.html#the-last-command-how-to-get-help"><i class="fa fa-check"></i><b>10.5</b> The last command: how to get help</a></li>
<li class="chapter" data-level="10.6" data-path="wild.html"><a href="wild.html#the-strausz-method-for-improving-in-r"><i class="fa fa-check"></i><b>10.6</b> The Strausz method for improving in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Are you ready for R? A Workbook for R for Political Science and Beyond: Version 3.0</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tidyverse" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Welcome to the tidyverse<a href="tidyverse.html#tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="install-tidyverse" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Installing packages<a href="tidyverse.html#install-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the nice things about R is that users can create their own libraries of commands. These can be extremely powerful and useful tools. There is an excellent set of tools that are in a library called the “tidyverse.” To install the tidyverse on your local computer, first, make sure that your computer is attached to the internet. Second, enter this command into the Console of RStudio and press Enter:</p>
<pre><code>install.packages(&quot;tidyverse&quot;)</code></pre>
<p>Once you hit enter, you should see some action in your Console (what it says will depend on what version of R you are using). Some of it might be in red, but don’t worry about it. Now you have installed the tidyverse! We will regularly work with the tools that this library makes possible for us.</p>
</div>
<div id="exploring" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Exploring dataframes<a href="tidyverse.html#exploring" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To begin exploring dataframes, open the project that you made in the last lab. There are two ways that you can do this:</p>
<ol style="list-style-type: decimal">
<li>You can open RStudio, go to File, open project, and navigate to the file called Scope and Methods labs.</li>
<li>You can navigate to the folders that you made last lab and double click the file called “Scope and Methods Labs,” like the circled file below:</li>
</ol>
<p><img src="images/tidyverse_1_openproject.png" width="60%" /></p>
<p>If you followed the instructions in section <a href="getting-started.html#first-script">1.5</a>, you should see an object called anes2024 in your environment. To load the other two dataframes that you will need to use this workbook, copy and paste these two commands into your Console, one by one:</p>
<pre><code>load(&quot;Data/states2025.Rda&quot;) </code></pre>
<pre><code>load(&quot;Data/world2025.Rda&quot;) </code></pre>
<p>If those commands don’t work, you should load anes2024 (if you haven’t already), states2025, and world2025 using the instructions from section <a href="getting-started.html#wont-load">1.6</a>.</p>
<p>Those files are the dataframes that we will be doing most of our analysis on in this class. As I mentioned in the last chapter, a dataframe is essentially a group of vectors attached to one another, and is an extremely useful way of storing data for analysis. Here is a quick summary of those three dataframes:</p>
<ul>
<li>anes2024 is a snippet of the American National Election Survey, a survey that has been conducted at every election since 1948 by scholars based out of the University of Michigan and Stanford. This dataframe that I created only looks at the 2024 election. You can find more information about ANES at their website, <a href="https://electionstudies.org/">https://electionstudies.org/</a></li>
<li>states2025 is a dataframe with information about US States. It is based on data that I collected from a variety of sources. You can find information about the source of each variable in the file “States 2025 codebook.pdf”, which is in the codebooks folder that you downloaded with the other class materials in section <a href="getting-started.html#add-files">1.3</a>. If you’d like to suggest additional variables to go in this dataset, please <a href="https://www.michaelstrausz.com/contact">contact me.</a></li>
<li>world2025 is a dataframe with information about most of the countries in the world. It is based on data that I collected from a variety of sources. You can find information about the source of each variable in the file “World 2025 codebook.pdf”, which is in the codebooks folder that you downloaded with the other class materials in section <a href="getting-started.html#add-files">1.3</a>. If you’d like to suggest additional variables to include, please <a href="https://www.michaelstrausz.com/contact">contact me.</a></li>
</ul>
<p>To begin, let’s take a look at the anes2024 dataset using the “View()” command (note that “View” is capitalized, unlike many R commands). Enter this command into the Console and then hit Enter:</p>
<pre><code>View(anes2024)</code></pre>
<p>When you hit enter, the following should come up on your screen:
<img src="images/tidyverse_2_view.png" width="90%" /></p>
<p>This is a neat visualization of the ANES data. Each row represents one case. Since ANES is a survey, each case is a single individual who took the survey. Each column represents a variable: something that the survey designers wanted to measure about the people taking the survey. Look at row #1. That describes a person who is 50-years-old, married, formerly active duty in the military, not a union member, Hispanic, etc. If you want to see what all of the variables mean, you can look at the file ANES 2024 codebook, which you should have downloaded in section <a href="getting-started.html#add-files">1.3</a> as part of the “codebooks” folder.</p>
<p>Now let’s say that we want to know a bit more about the age variable. How old was the average person that took our survey? To answer, we need to learn two more R commands: the “$” and the command “summary.” The “$” command helps us identify single columns within a dataframe. So, if we just want to see the age column, you can type this in the Console:</p>
<pre><code>anes2024$age</code></pre>
<p>When you do this, you will see that R gives you the age of every single person who took the survey. Kind of interesting, but not all that useful. So, let’s try something else. Type summary(anes2024$age) into the Console, and you get these results:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="tidyverse.html#cb12-1" tabindex="-1"></a><span class="fu">summary</span>(anes2024<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   18.00   39.00   54.00   53.15   68.00   80.00     279</code></pre>
<p>This gives you a lot of useful information! You can see that the youngest age in the dataframe is 18 (likely because they were not surveying minors), and the oldest is 80.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> You will also see that the median age is 54 and the mean is 53.15. And, you will see that there are 279 NAs. “NA” is what R reports when it does not have data in a particular variable. So, there are 279 cases for whom we don’t have data on their ages.</p>
<p>The “summary” command is very useful with numeric data, like age. However, what if you have a variable like “marital,” which measures the marital status of individuals? The mean and median of this variable would not be meaningful, but we might want to know how many married, single, divorced, etc. people there are in our dataframe. To get this information, we can use the “table” command, like this:</p>
<pre><code>table(anes2024$marital)</code></pre>
<p>That command generates this output:</p>
<pre><code>## 
##      divorced       married never married     separated       widowed 
##           771          2745          1242            91           414</code></pre>
<p>In other words, our dataframe has 771 divorced people, 2745 married people, 1242 never married people, etc. Useful stuff!</p>
</div>
<div id="org-script" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Organizing your scripts<a href="tidyverse.html#org-script" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As you use R you will generate a lot of script files, and if you are not careful you might find yourself forgetting what some of your scripts are for. This is where the # characters can be really helpful. You can leave notes to yourself.</p>
<p>This is a nice way to add headers to R script files:</p>
<pre><code>####################################
# Your name
# Project, Purpose of R file
# Date started : Date last modified
####################################</code></pre>
<p>Then, when you open a script file, you can see right away when you made it and what it is for. You can customize this header as is helpful to you.</p>
</div>
<div id="welcome-to-the-tidyverse" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Welcome to the tidyverse<a href="tidyverse.html#welcome-to-the-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Perhaps the code package that has had the biggest impact on how people do R in the last few years had been the “tidyverse”. To take advantage of this great library which you installed in section <a href="tidyverse.html#install-tidyverse">2.1</a>, you first have to activate it. You will have to do this step every time that you open R, so I often put it at the top of my script files.</p>
<p>To follow along, open a new script file and save it in your scripts folder as “chapter 2 practice.” Copy and paste this onto the page:</p>
<pre><code>####################################
# Your name
# 20093 Chapter 2, Practice exercises
# Date started : Date last modified
####################################

#libraries------------------------------------------
library(tidyverse)</code></pre>
<p>Now select all the text on this page, run it, and then save it. You should see something like this in your Console:</p>
<pre><code>── Attaching core tidyverse packages ────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ──────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package to force all conflicts to become errors</code></pre>
<p>Don’t worry about the warning messages. The list of packages are the libraries of commands that come with the tidyverse library. The two that we will be using the most are <strong>ggplot2</strong>, which is terrific for graphing, and <strong>dplyr</strong>, which is great for managing data. Since you have installed the tidyverse, you will not have to install those packages separately – you already have them installed.</p>
<div id="introducing-the-pipe-in-tidyverse" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Introducing the ‘pipe’ in tidyverse<a href="tidyverse.html#introducing-the-pipe-in-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have access to the tidyverse, we will use a few of the commands that are available to us through the dplyr package to get a better look at some of our data. Before we can do that, however, we need to learn about the somewhat strange feature of dplyr, the “pipe.” The pipe is this set of characters:</p>
<pre><code>%&gt;%</code></pre>
<p>You can always type those three characters to build a pipe, but you can also type Ctrl-Shift-M on a Windows machine or Cmd + Shift + M on a Mac. I am going to repeat this, in bold, because it is an <em>extremely</em> useful keyboard shortcut. <strong>You can always type those three characters to build a pipe, but you can also type Ctrl-Shift-M on a Windows machine or Cmd + Shift + M on a Mac.</strong></p>
<p>The pipe means “and then.” Let’s try an example, using the glimpse() command that is available in the tidyverse.</p>
<p>Try entering this command into your script file:</p>
<pre><code>anes2024 %&gt;% 
  glimpse() #taking a different kind of look at our dataframe</code></pre>
<p>Highlight that text and run that command. You should see a lot of output in the Console. If you scroll up a bit in the Console, you should see something like this (this is just the first 12 variables in this dataframe; you will have access to more on your screen):</p>
<pre><code>## Rows: 5,521
## Columns: 12
## $ age        &lt;int&gt; 50, 41, 44, 45, 80, 75, 41, 49, 45, 41, 59, 34, 42, 70, 58…
## $ female     &lt;dbl&gt; 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0…
## $ marital    &lt;chr&gt; &quot;married&quot;, &quot;married&quot;, &quot;married&quot;, &quot;married&quot;, &quot;widowed&quot;, &quot;di…
## $ mil        &lt;chr&gt; &quot;formerly active duty&quot;, &quot;never served&quot;, &quot;never served&quot;, &quot;n…
## $ union      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0…
## $ race       &lt;chr&gt; &quot;Hispanic&quot;, &quot;Asian or Pacific Islander&quot;, &quot;White&quot;, &quot;Asian o…
## $ children   &lt;int&gt; 0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0…
## $ landline   &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0…
## $ smartphone &lt;dbl&gt; 1, 1, 1, NA, NA, 1, 1, 1, NA, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…
## $ passport   &lt;dbl&gt; 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0…
## $ trans      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gayLesbian &lt;chr&gt; &quot;straight&quot;, &quot;straight&quot;, &quot;straight&quot;, &quot;straight&quot;, &quot;straight&quot;…</code></pre>
<p>This is giving us information about the dataframe anes2024. At the top, you can see that the dataframe has 5,521 rows. Since this is a survey, and each row represents one person that was surveyed, that tells us that the anes2024 dataframe represents a survey of 5,521 people. On the output above, you can see that the dataframe has 12 columns (because I told R to only display the first 12.) If you ran the command, you should see that the full dataframe has 83 columns, which means that the dataframe measures 83 variables. The glimpse() command in the tidyverse gives us a bit of information about each of these variables. On the left of the output you can see all of the variable names (age, marital, etc.). And then just to the right of that you can see the way that R is classifying those variables (&lt;int&gt;, &lt;chr&gt;, &lt;ord&gt;, etc.). We will learn a bit more about those classifications in future chapters. To the right of those classifications you can see the first set of values of each variable.</p>
</div>
<div id="select-in-tidyverse" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> select() in tidyverse<a href="tidyverse.html#select-in-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Many dataframes are quite large, and you might find yourselves wanting to focus on a few variables at a time. The command select() can be helpful for this. Let’s say that you want to focus in on how many guns people have in their homes and their feelings about the NRA. In that case, you would want to select the variables “ft_nra” and “guns”, which you can do like this:</p>
<pre><code>anes2024 %&gt;% 
  select(guns, ft_nra) #focusing in on a few variables</code></pre>
</div>
<div id="a-warning-about-the-select-command" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> A warning about the select() command<a href="tidyverse.html#a-warning-about-the-select-command" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Unfortunately, some of the packages that we will be installing in future labs also use the command select. If you ever run “select” and have more than one of these packages installed, R will give an error. When you get that error, you can add “dplyr::” before select(), to tell R to look at the select() in the dplyr library (which comes with the tidyverse). Here is how the above command would look with that modification:</p>
<pre><code>anes2024 %&gt;% 
  dplyr::select(guns, ft_nra) #focusing in on a few variables</code></pre>
<p>If you run either of these commands (with or without the dplyr::), and scroll up a bit in the Console, you will see output that begins like this:</p>
<pre><code>##    guns ft_nra
## 1     1     60
## 2     0     50
## 3     0      0
## 4     0     70
## 5     0     60
## 6     0     30
## 7     0     85
## 8     0     50
## 9     0     75
## 10    0     50</code></pre>
<p>This is a way of displaying dataframes that is unique to the tidyverse called a “tibble.” Each row represents a case, and each column represents a variable (except for the leftmost column, which is just the case number. Looking at case #1, you can see that that person owns 3 guns, and rates the NRA 50 out of 100. Case #2 also rates the NRA 50, but owns no guns.</p>
<p>Notice that the dataframe that had been so large before, with 68 columns, now only has 2 columns. If you want to use that glimpse() command from above to just get summary information about each of our variables, you can use a second pipe (%&gt;%) like this:</p>
<pre><code>anes2024 %&gt;% 
  select(guns, ft_nra) #focusing in on a few variables%&gt;%
  glimpse() #taking a different kind of look at our dataframe</code></pre>
</div>
<div id="arrange-in-tidyverse" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> arrange() in tidyverse<a href="tidyverse.html#arrange-in-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What if we want to see what the people in our sample with the most and fewest guns thought about the NRA? To do that, we can arrange our dataframe from smallest to largest or from largest to smallest on any of our variables. Or, with variables that include text, we can sort according to alphabetic or reverse alphabetic order. We can use the arrange() command to do that:</p>
<pre><code>anes2024 %&gt;% 
  select(guns, ft_nra) %&gt;% #focusing in on a few variables
  arrange(guns) #sorting this variable from smallest to largest</code></pre>
<p>When we run the above command, the Console shows us the feeling about the NRA by the people with the fewest guns first, and then on to the people with more guns. But what if we want to see the largest values on the “guns” variable first? To do that, we need to use desc() to modify arrange() like this:</p>
<pre><code>anes2024 %&gt;% 
  select(guns, ft_nra) %&gt;% #focusing in on a few variables
  arrange(desc(guns)) #sorting this variable from largest to smallest</code></pre>
</div>
<div id="glimpse-in-tidyverse" class="section level3 hasAnchor" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> glimpse() in tidyverse<a href="tidyverse.html#glimpse-in-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, combining all of the commands that we learned today, we can use glimpse() to see information about each of our variables in this simplified version of our dataframe. To do that, we will need a third pipe:</p>
<pre><code>anes2024 %&gt;% 
  select(guns, ft_nra) %&gt;% #focusing in on a few variables
  arrange(desc(guns)) %&gt;% #sorting this variable from largest to smallest
  glimpse() #taking a different kind of look at our dataframe</code></pre>
</div>
</div>
<div id="review-of-this-chapters-commands-1" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Review of this chapter’s commands<a href="tidyverse.html#review-of-this-chapters-commands-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table>
<colgroup>
<col width="7%" />
<col width="85%" />
<col width="6%" />
</colgroup>
<thead>
<tr>
<th align="left">Command</th>
<th align="left">Purpose</th>
<th align="left">Library</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">install.packages(““)</td>
<td align="left">To install new packages, or libraries of R commands. You have to do this only once on your computer per library when your computer is connected to the internet so that it will download the relevant library.</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">View()</td>
<td align="left">Displays a dataframe as a spreadsheet. Notice that the word “View” is capitalized.</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">summary()</td>
<td align="left">Displays summary information (like mean and median) about a numeric variable. To call a variable, use a dollar sign. So, like this: “summary(dataframe$variable)”</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">table()</td>
<td align="left">Displays the number of times each value of a variable appears in a dataframe. Most useful for variables with a relatively small number of possible values. To call a variable, use a dollar sign. So, like this: “table(dataframe$variable)”</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">library()</td>
<td align="left">To ask R to load a library into your session. You must use this command every time that you open R if you want it to use a particular library.</td>
<td align="left">Base R</td>
</tr>
<tr>
<td align="left">%&gt;%</td>
<td align="left">The “pipe.” Useful with manipulating data in the tidyverse.</td>
<td align="left">dplry (tidyverse)</td>
</tr>
<tr>
<td align="left">glimpse()</td>
<td align="left">Display general information about a dataset, including looking at the variable names, types, and a few values in rows. Often preceded by a pipe.</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
<tr>
<td align="left">select()</td>
<td align="left">Allows you to select a few variables to focus on. Often preceded by a pipe. You can use the variable names without dollar signs.</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
<tr>
<td align="left">arrange(desc())</td>
<td align="left">Sorts a dataframe from largest to smallest values of a particular variable (or in reverse-alphabetical order). Often preceded by a pipe. You can use the variable names without dollar signs.</td>
<td align="left">dplyr (tidyverse)</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>If you look in the codebook, you will see that the survey codes everyone 80 and over as 80.<a href="tidyverse.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="getting-started.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="graphing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-tidyverse.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
